"""reports/metrics.md (S5): the evidence for PLAN §5 S5 "Done when", the gbar table of Rule D1, and the metric
library run over every stored run. Reads results/tables/{s5_checks.json, metrics.parquet, gbar.parquet}."""

from __future__ import annotations

import json

import numpy as np
import pandas as pd

from ..store.paths import reports_dir, tables_dir


def _f(x, fmt="{:.3g}"):
    if x is None or (isinstance(x, float) and not np.isfinite(x)):
        return "–"
    return fmt.format(x)


def _table(df: pd.DataFrame) -> list[str]:
    cols = list(df.columns)
    out = ["| " + " | ".join(str(c) for c in cols) + " |", "|" + "|".join("---" for _ in cols) + "|"]
    for _, r in df.iterrows():
        out.append("| " + " | ".join(str(r[c]) for c in cols) + " |")
    return out


def _d1_exercise(root) -> list[str]:
    """D1's machinery on the stored curves with the q average relaxed (the stored runs have q = 1.5 only)."""
    from ..stats import d1
    cur = d1.curves_from_store(root)
    if cur.empty:
        return ["No stored run matches the D1 filters."]
    res = d1.run_d1(cur, gbar={}, q_values=None)
    ch = res["choices"]
    if ch.empty:
        return ["No configuration has data."]
    if "chosen" not in ch:
        return ["No configuration has data on every draw."]
    ch = ch[ch["chosen"].fillna(False).astype(bool) & (ch["pairing"] == "median")]
    piv = ch.pivot_table(index=["N", "k"], columns="arm", values="cfg_label", aggfunc="first").reset_index()
    return _table(piv)


def markdown(root=None) -> str:
    t = tables_dir(root)
    L = ["# Metric library and statistics (S5)", "",
         "Generated by `gsp metrics report` from `results/tables/s5_checks.json` (`gsp metrics checks`), "
         "`metrics.parquet` (`gsp aggregate`) and `gbar.parquet` (`gsp stats gbar`). Definitions: PLAN §1.7; code: "
         "`gsp/metrics/`, `gsp/stats/`.", ""]
    ck = json.loads((t / "s5_checks.json").read_text()) if (t / "s5_checks.json").exists() else None
    if ck:
        ex = ck["example"]
        L += ["## 1. `example_metrics.py` reproduced", "",
              f"The frozen copy `tests/legacy/example_metrics.py` is run as is and every quantity it prints is "
              f"recomputed by the library (`MetricContext`, `quality.py`). **Max abs error {ex['max_error']:.1e}** "
              "(requirement 1e-12):", ""]
        L += _table(pd.DataFrame([{"quantity": k, "abs error": f"{v:.1e}"} for k, v in ex["errors"].items()]))
        L += ["", f"The exact AR_best_S (S = {ex['S']}) is {ex['AR_best_S_exact']:.5f}; the script's 20000-row "
              f"estimate is {ex['AR_best_S_script']:.5f} ± {ex['AR_best_S_se']:.5f} "
              f"({ex['exact_vs_script_in_se']:.2f} standard errors apart).", ""]
        sd = ck["simdiff"]
        L += ["## 2. Simulation difficulty: numpy vs quimb", "",
              f"Over the {sd['n_states']} stored final states: max |F_numpy(chi) − F_quimb(chi)| over the chi grid "
              f"**{sd['max_F_diff']:.1e}**, max entropy difference {sd['max_S_diff']:.1e}, chi* mismatches "
              f"{sd['chi_star_mismatch']}. The cross-test passes 1e-10, so the default engine is "
              f"**{sd['default_engine']}** (PLAN §1.7).", "",
              "`simdiff` on Haar-random states (the worst case: chi* near 2^(n/2)), one call:", ""]
        L += _table(pd.DataFrame([{"n": r["n"], "engine": r["engine"], "wall (s)": _f(r["wall_s"], "{:.2f}"),
                                   "chi*": r["chi_star"], "sweeps": r["n_sweeps"],
                                   "work (MB)": _f((r["work_bytes"] or 0) / 1e6, "{:.0f}")}
                                  for r in sd["timing_random"]]))
        L += ["", "## 3. Rules on synthetic data with a known answer", "", "**D1** (planted per-draw difference "
              "A1 − A0 over 30 draws × 3 q, R = 5; B = 10^4, where the curves have saturated):", ""]
        L += _table(pd.DataFrame([{"planted": r["planted"], "pairing": r["pairing"], "median d": _f(r["median_d"]),
                                   "p (Holm, m = 4)": _f(r["p_holm"]), "delta*": r["delta_star"],
                                   "outcome": r["outcome"]} for r in ck["d1"]["rows"]]))
        L += ["", "**D2** (2000 fold resamples):", ""]
        L += _table(pd.DataFrame([{"truth": r["truth"], "planted": r["planted"], "separable": r["separable"],
                                   "Spearman rho": _f(r["rho"], "{:.2f}"), "RMSE ratio": _f(r["ratio"], "{:.3f}"),
                                   "ratio 95 %": f"[{_f(r['ratio_ci'][0], '{:.3f}')}, {_f(r['ratio_ci'][1], '{:.3f}')}]",
                                   "preferred": r["preferred"], "exponent": _f(r["exponent"], "{:.3f}"),
                                   "exponent 95 %": f"[{_f(r['exponent_ci'][0], '{:.3f}')}, "
                                                    f"{_f(r['exponent_ci'][1], '{:.3f}')}]"}
                                  for r in ck["d2"]["diagnostics"]]))
        L += ["", "Verdicts over the two voting diagnostics: " + "; ".join(
            f"planted *{k}* → **{v}**" for k, v in ck["d2"]["verdicts"].items()), ""]
        L += ["**C1** growth exponent of the leakage vs D (max over 10 circuits):", ""]
        L += _table(pd.DataFrame([{"truth": r["truth"], "seed": r["seed"], "exponent": _f(r["exponent"], "{:.3f}"),
                                   "95 %": f"[{r['ci'][0]:.3f}, {r['ci'][1]:.3f}]", "class": r["class"]}
                                  for r in ck["c1"]["rows"]]))
        c2 = ck["c2"]
        L += ["", "**C2** KL to Haar^(d), 5000 pairs, 75 bins, 1000 resamples: " + "; ".join(
            f"{k}: {v['kl']:.4f} [{v['lo']:.4f}, {v['hi']:.4f}]" for k, v in c2.items()), ""]
    gp = t / "gbar.parquet"
    if gp.exists():
        g = pd.read_parquet(gp)
        piv = g.pivot_table(index="N", columns="kind", values="gbar", aggfunc="first").reset_index()
        piv["delta* (primary pairs)"] = [max(0.02, s, b) for s, b in zip(piv["sector"], piv["band"])]
        for c in ("band", "sector", "delta* (primary pairs)"):
            piv[c] = piv[c].map(lambda x: f"{x:.4f}")
        L += ["## 4. Rule D1's gap threshold, measured on the frozen set", "",
              "gbar_arm(N) = median over the N's 90 instances of the median adjacent spacing of the distinct "
              "normalized objective values the arm can return: the D1 sector (ring · violation · K = 12, GA list) for "
              "A1 / A2c / A4, the band for A0 / A3. delta*(pair) = max{0.02, gbar_A, gbar_B}. Every primary pair "
              "contains A1, so delta* is the sector's gbar there:", ""]
        L += _table(piv)
        L += [""]
    mp = t / "metrics.parquet"
    if mp.exists():
        df = pd.read_parquet(mp)
        L += ["## 5. The library over the stored runs", "",
              f"`gsp metrics finalize` (GPU) wrote samples.npz + postrun.json for every stored run, then "
              f"`gsp aggregate` wrote {len(df)} rows × {df.shape[1]} columns. Runs with an anomaly: "
              f"**{int((df['anomalies'] != '').sum())}**.", ""]
        rows = []
        for arm, g in df.groupby("arm"):
            rows.append({"arm": arm, "runs": len(g), "N": ",".join(str(x) for x in sorted(g["N"].unique())),
                         "AR_F med": _f(g["st_ar_f"].median(), "{:.3f}"),
                         "AR_best_S med": _f(g["ar_best_S"].median(), "{:.3f}"),
                         "no feasible shot": int(g["ar_best_S_sampled"].isna().sum()),
                         "min tail p": _f(g["sample_tail_p"].min()),
                         "max replay": _f(g["replay_max_abs"].max()),
                         "max state−record": _f(g["chk_state_vs_record"].max()),
                         "chi* range": f"{int(g['sd_chi_star'].min())}–{int(g['sd_chi_star'].max())}",
                         "S/log2K range": ("–" if g["sd_S_over_log2K"].isna().all() else
                                           f"{g['sd_S_over_log2K'].min():.2f}–{g['sd_S_over_log2K'].max():.2f}"),
                         "conv t med": _f(g["conv_t"].median(), "{:.0f}"),
                         "sector join": int(g.get("pre_available", pd.Series(dtype=bool)).fillna(False).sum())})
        L += _table(pd.DataFrame(rows))
        L += ["", "- *tail p*: the exact probability, under the stored state, of a best-of-1000 value at least as "
              "extreme as the one sampled (or of no feasible shot); the anomaly threshold is 1e-4.",
              "- *replay*: max |ψ_rebuilt − final_state.npy| after rebuilding the circuit from run.json.",
              "- *state−record*: the recomputed AR_F / p_feas / ε̃ / p_opt / p_top10 / energy vs run.json.",
              "- The A1 run without a sector join is the ad hoc N05e002 reproduction (rejected draw, BF list built in "
              "memory, no sector file).", ""]
    L += ["## 6. Rule D1 on the stored curves (plumbing only)", "",
          "The stored runs hold one instance per N at q = 1.5 (S4's smoke, reproduction and anneal checks), so D1 as "
          "written (mean over the three q, 30 draws) has **no data** at every budget (`gsp stats d1`). With the q "
          "average relaxed, the configuration c*(B) each arm would take at B = 10^k (median-of-R pairing):", ""]
    try:
        L += _d1_exercise(root)
    except Exception as exc:  # pragma: no cover (report only)
        L += [f"(failed: {exc!r})"]
    L += [""]
    return "\n".join(L)


def write(root=None):
    p = reports_dir() / "metrics.md"
    p.write_text(markdown(root))
    return p
