"""Generate gsp/circuits/interp.py (the interpreter kernel, S3). Run from GSP/:

    ~/anaconda3/envs/gsp/bin/python scripts/gen_interp_kernel.py

The branch ladder (one fixed-arity `rx.ctrl` / `ry.ctrl` per control count) is mechanical, so the kernel file
is generated rather than hand-written. `tests/test_preserving.py::test_interp_kernel_is_generated` checks that
the committed file equals this script's output.
"""

from pathlib import Path

MAXC = 19

HEAD = '''"""The gate-list interpreter kernel (S3): ONE `@cudaq.kernel`, compiled once per process, that runs any
gate list of `gsp.compile.decompose` passed as data (`gsp.circuits.program.encode`).

GENERATED by `scripts/gen_interp_kernel.py`; regenerate rather than hand-edit.

Why (CUDA-Q 0.15.1, RTX 4080; STATUS S3, reports/mixer_counts.md): a builder kernel (`cudaq.make_kernel`,
PLAN §2.4) is JIT-compiled per circuit (1.2 s for the 4,300-gate A1 circuit at n = 14, L = 9) and `get_state`
re-compiles it on EVERY call (1.1 s there). This kernel compiles once per process (~0.4 s) and never again,
whatever the list; `get_state` then costs what `observe` costs (53 ms there; the builder's steady `observe`
is 1.6x faster, 33 ms). The multi-controlled rotations take their controls from a runtime list by
dispatching on the arity (1..{MAXC} controls, n <= {NQ}): each branch is a fixed-arity `rx.ctrl` / `ry.ctrl`,
which the kernel language supports.

Opcodes: 0 x, 1 h, 2 s, 3 sdg, 4 t, 5 tdg, 6 cx (control ctl[cs]), 7 rx, 8 ry, 9 rz,
10 mc-rx, 11 mc-ry (controls ctl[cs .. cs + nc - 1], closed). Angle = coef, or coef * p[pidx] if pidx >= 0.
"""

import cudaq


@cudaq.kernel
def kernel_program(n: int, op: list[int], tgt: list[int], cs: list[int], nc: list[int], ctl: list[int],
                   coef: list[float], pidx: list[int], p: list[float]):
    q = cudaq.qvector(n)
    for g in range(len(op)):
        o = op[g]
        tq = tgt[g]
        ang = coef[g]
        if pidx[g] >= 0:
            ang = coef[g] * p[pidx[g]]
        if o == 0:
            x(q[tq])
        elif o == 1:
            h(q[tq])
        elif o == 2:
            s(q[tq])
        elif o == 3:
            sdg(q[tq])
        elif o == 4:
            t(q[tq])
        elif o == 5:
            tdg(q[tq])
        elif o == 6:
            x.ctrl(q[ctl[cs[g]]], q[tq])
        elif o == 7:
            rx(ang, q[tq])
        elif o == 8:
            ry(ang, q[tq])
        elif o == 9:
            rz(ang, q[tq])
'''


def source() -> str:
    body = []
    for opc, gate in ((10, "rx"), (11, "ry")):
        body += [f"        elif o == {opc}:", "            c = cs[g]", "            k = nc[g]"]
        for k in range(1, MAXC + 1):
            ctls = ", ".join("q[ctl[c]]" if i == 0 else f"q[ctl[c + {i}]]" for i in range(k))
            body += [f"            {'if' if k == 1 else 'elif'} k == {k}:", f"                {gate}.ctrl(ang, {ctls}, q[tq])"]
    return HEAD.replace("{MAXC}", str(MAXC)).replace("{NQ}", str(MAXC + 1)) + "\n".join(body) + "\n"


if __name__ == "__main__":
    out = Path(__file__).resolve().parents[1] / "gsp" / "circuits" / "interp.py"
    out.write_text(source())
    print(f"wrote {out}")
