"""Generate gsp/circuits/dbqite_kernel.py (the DB-QITE kernel, S8). Run from GSP/:

    ~/anaconda3/envs/gsp/bin/python scripts/gen_dbqite_kernel.py

Like `gen_layered_kernel.py`, the arity ladder of the multi-controlled Ry (the star prep's transitions) is mechanical,
so the file is generated. `tests/test_dbqite.py::test_dbqite_kernel_is_generated` checks the committed file equals
this output.
"""

from pathlib import Path

MAXC = 19

HEAD = '''"""The DB-QITE kernel (S8): ONE `@cudaq.kernel`, compiled once per process, that runs the unrolled recursion
U_k of arms A4 / A6 (PLAN §1.5, D-2) from a short TOKEN list instead of the 3^k-long gate list.

GENERATED by `scripts/gen_dbqite_kernel.py`; regenerate rather than hand-edit.

U_{k+1} = e^{i r_k H} U_k e^{i r_k |0..0><0..0|} U_k^dagger e^{-i r_k H} U_k (operator order), i.e. in circuit order
U_k, cost(+r_k), U_k^dagger, phase(r_k), U_k, cost(-r_k). The gate data of the two base segments (U_0 = the start
circuit, and the cost exponential e^{-i a H}) is passed once; a token says which segment to run and with which
angle (`gsp.circuits.dbqite.recursion_tokens` builds the list; adjacent cost tokens are merged there, exactly):
  tk[t] = 0  U_0 forward
          1  U_0 inverse (the segment's gates in reverse order, every angle negated; x / h / cx are self-inverse)
          2  the cost segment with angle a = ta[t]: exp(-i a H) (slot-1 gates take coef * a)
          3  the open-controlled phase e^{i a |0...0><0...0|}: X on every qubit, r1.ctrl(a) on qubit n - 1 with
             qubits 0..n-2 as controls, X on every qubit
Why (CUDA-Q 0.15.1; STATUS S4 / S8): kernel arguments cost ~0.8 us per list element per call, and U_k has
~3^k x (|U_0| + |cost|) gates; its token list is (5 * 3^k - 3) / 2 long before merging.

Arguments (built by `gsp.circuits.dbqite.DBCircuit.args`):
  code[g] = op + 16 * (target + 32 * (n_controls + 32 * (slot + 4 * ctl_start)))   (as `program.encode_layered`)
      op: 0 x, 1 h, 6 cx, 7 rx, 8 ry, 9 rz, 11 mc-ry, 12 crz (the opcodes of `program.OPCODES`);
      slot: 0 constant angle coef[g], 1 coef[g] * a (the token's angle);
      controls ctl[ctl_start .. ctl_start + n_controls - 1] (closed; cx / crz use one).
  seg = [u0_begin, u0_end, cost_begin, cost_end] (indices into code / coef).
  tk, ta: the tokens (kinds and angles).
Multi-controlled Ry dispatches on its arity (1..{MAXC} controls, n <= {NQ}).
"""

import cudaq


@cudaq.kernel
def kernel_dbqite(n: int, code: list[int], coef: list[float], ctl: list[int], seg: list[int], tk: list[int],
                  ta: list[float]):
    q = cudaq.qvector(n)
    for t in range(len(tk)):
        kd = tk[t]
        a = ta[t]
        if kd == 3:
            x(q)
            r1.ctrl(a, q.front(n - 1), q[n - 1])
            x(q)
        else:
            g0 = seg[0]
            g1 = seg[1]
            if kd == 2:
                g0 = seg[2]
                g1 = seg[3]
            sgn = 1.0
            if kd == 1:
                sgn = -1.0
            for i in range(g1 - g0):
                g = g0 + i
                if kd == 1:
                    g = g1 - 1 - i
                cc = code[g]
                o = cc % 16
                cc = cc // 16
                tq = cc % 32
                cc = cc // 32
                k = cc % 32
                cc = cc // 32
                sl = cc % 4
                c = cc // 4
                ang = coef[g]
                if sl == 1:
                    ang = coef[g] * a
                ang = sgn * ang
                if o == 12:
                    rz.ctrl(ang, q[ctl[c]], q[tq])
                elif o == 9:
                    rz(ang, q[tq])
                elif o == 0:
                    x(q[tq])
                elif o == 6:
                    x.ctrl(q[ctl[c]], q[tq])
                elif o == 1:
                    h(q[tq])
                elif o == 8:
                    ry(ang, q[tq])
                elif o == 7:
                    rx(ang, q[tq])
'''


def source() -> str:
    body = ["                elif o == 11:"]
    for k in range(1, MAXC + 1):
        ctls = ", ".join("q[ctl[c]]" if i == 0 else f"q[ctl[c + {i}]]" for i in range(k))
        body += [f"                    {'if' if k == 1 else 'elif'} k == {k}:",
                 f"                        ry.ctrl(ang, {ctls}, q[tq])"]
    return HEAD.replace("{MAXC}", str(MAXC)).replace("{NQ}", str(MAXC + 1)) + "\n".join(body) + "\n"


if __name__ == "__main__":
    out = Path(__file__).resolve().parents[1] / "gsp" / "circuits" / "dbqite_kernel.py"
    out.write_text(source())
    print(f"wrote {out}")
