"""Generate gsp/circuits/layered.py (the layered kernel, S4). Run from GSP/:

    ~/anaconda3/envs/gsp/bin/python scripts/gen_layered_kernel.py

Like `gen_interp_kernel.py`, the arity ladder of the multi-controlled rotations is mechanical, so the file is
generated. `tests/test_arms.py::test_layered_kernel_is_generated` checks the committed file equals this output.
"""

from pathlib import Path

MAXC = 19

HEAD = '''"""The layered program kernel (S4): ONE `@cudaq.kernel`, compiled once per process, that runs every A0 / A1 / A2
circuit of the harness: a start segment once, then one layer segment L times, the layer's angles bound to
(gamma_l, beta_l) = (p[l], p[L + l]).

GENERATED by `scripts/gen_layered_kernel.py`; regenerate rather than hand-edit.

Why (CUDA-Q 0.15.1, RTX 4080; STATUS S4): every list element of a kernel's arguments costs ~0.8 us of argument
conversion per call. The flat interpreter (`interp.py`) passes 8 lists as long as the whole circuit (~35,000
elements for the 4,400-gate A1 circuit at n = 14, L = 9: half of its 50 ms per call). Here the gate data of one
layer is passed once (L times shorter) and packed into one integer per gate.

Arguments (built by `gsp.circuits.program.encode_layered`):
  code[g] = op + 16 * (target + 32 * (n_controls + 32 * (slot + 4 * ctl_start)))
      op: 0 x, 1 h, 6 cx, 7 rx, 8 ry, 9 rz, 10 mc-rx, 11 mc-ry, 12 crz (the opcodes of `program.OPCODES`);
      slot: 0 constant angle coef[g], 1 coef[g] * gamma_l, 2 coef[g] * beta_l;
      controls ctl[ctl_start .. ctl_start + n_controls - 1] (closed; cx / crz use one).
  seg = [start_begin, start_end, layer_begin, layer_end] (indices into code / coef).
  p = [gamma_1 .. gamma_L, beta_1 .. beta_L].
Multi-controlled rotations dispatch on their arity (1..{MAXC} controls, n <= {NQ}).
"""

import cudaq


@cudaq.kernel
def kernel_layered(n: int, L: int, code: list[int], coef: list[float], ctl: list[int], seg: list[int],
                   p: list[float]):
    q = cudaq.qvector(n)
    for rep in range(L + 1):
        g0 = seg[0]
        g1 = seg[1]
        if rep > 0:
            g0 = seg[2]
            g1 = seg[3]
        ell = rep - 1
        for g in range(g0, g1):
            cc = code[g]
            o = cc % 16
            cc = cc // 16
            tq = cc % 32
            cc = cc // 32
            k = cc % 32
            cc = cc // 32
            sl = cc % 4
            c = cc // 4
            ang = coef[g]
            if sl == 1:
                ang = coef[g] * p[ell]
            elif sl == 2:
                ang = coef[g] * p[L + ell]
            if o == 12:
                rz.ctrl(ang, q[ctl[c]], q[tq])
            elif o == 9:
                rz(ang, q[tq])
            elif o == 0:
                x(q[tq])
            elif o == 6:
                x.ctrl(q[ctl[c]], q[tq])
            elif o == 7:
                rx(ang, q[tq])
            elif o == 1:
                h(q[tq])
            elif o == 8:
                ry(ang, q[tq])
'''


def source() -> str:
    body = []
    for opc, gate in ((10, "rx"), (11, "ry")):
        body += [f"            elif o == {opc}:"]
        for k in range(1, MAXC + 1):
            ctls = ", ".join("q[ctl[c]]" if i == 0 else f"q[ctl[c + {i}]]" for i in range(k))
            body += [f"                {'if' if k == 1 else 'elif'} k == {k}:",
                     f"                    {gate}.ctrl(ang, {ctls}, q[tq])"]
    return HEAD.replace("{MAXC}", str(MAXC)).replace("{NQ}", str(MAXC + 1)) + "\n".join(body) + "\n"


if __name__ == "__main__":
    out = Path(__file__).resolve().parents[1] / "gsp" / "circuits" / "layered.py"
    out.write_text(source())
    print(f"wrote {out}")
