"""Controllability of a confined sector: the Altafini check and the numerical-closure fallback
(PLAN §5 S2; proposal §6.5).

Setting. A sector is K kept strings u_1 < ... < u_K (lexicographic = ascending classical index,
D-9). The confined arms act inside span{|u_i>} with the drift H_0 = diag(E_1 .. E_K), E_i = H_obj(u_i)
(un-boosted; a positive boost rescales every gap and changes nothing here), and a coupling
H_1 = sum over coupled pairs (i, j) of |u_i><u_j| + |u_j><u_i|:
  ring       K edges (i, i+1 mod K) over the sorted list (PLAN §2.2)
  complete   K(K-1)/2 edges (i < j); also arm A4's condition, whose step couples every pair.

Altafini (2002): if the coupling graph is connected and the gaps |E_u - E_v| over the coupled pairs
are nonzero and pairwise distinct, {i H_0, i H_1} generates su(K), so d_eff = K^2 - 1.
Numerically: a gap is zero when it is <= rtol * scale, and two gaps coincide when they differ by
<= rtol * scale, with scale = max_i E_i - min_i E_i (the sector's energy spread) and rtol = 1e-9.
The margins (smallest gap / scale, smallest separation between two gaps / scale) are recorded.

Fallback (only where the check fails): `closure_dim` computes the dimension of the real Lie algebra
generated by {i H_0', i H_1} (H_0' = traceless part) by left-normed brackets: every Lie monomial in
two generators is a combination of left-normed ones, so it is enough to bracket each new basis
element with the two generators. All elements are traceless, so the result is d_eff directly.
"""

from __future__ import annotations

from dataclasses import asdict, dataclass

import numpy as np

RTOL = 1e-9
CONNECTIVITIES = ("ring", "complete")


def ring_edges(K: int) -> list[tuple[int, int]]:
    if K < 2:
        return []
    if K == 2:
        return [(0, 1)]
    return [(i, (i + 1) % K) for i in range(K)]


def complete_edges(K: int) -> list[tuple[int, int]]:
    return [(i, j) for i in range(K) for j in range(i + 1, K)]


def edges_for(connectivity: str, K: int) -> list[tuple[int, int]]:
    if connectivity == "ring":
        return ring_edges(K)
    if connectivity == "complete":
        return complete_edges(K)
    raise ValueError(f"connectivity must be one of {CONNECTIVITIES}, got {connectivity!r}")


def is_connected(K: int, edges) -> bool:
    if K <= 1:
        return True
    parent = list(range(K))

    def find(a):
        while parent[a] != a:
            parent[a] = parent[parent[a]]
            a = parent[a]
        return a

    for a, b in edges:
        ra, rb = find(a), find(b)
        if ra != rb:
            parent[ra] = rb
    return len({find(i) for i in range(K)}) == 1


@dataclass(frozen=True)
class AltafiniResult:
    K: int
    n_edges: int
    connected: bool
    gaps_nonzero: bool
    gaps_distinct: bool
    holds: bool
    d_eff: int                # K^2 - 1 if the condition holds, else -1 (use the closure)
    scale: float              # max E - min E over the sector
    min_gap_rel: float        # smallest coupled gap / scale
    min_sep_rel: float        # smallest difference between two coupled gaps / scale (inf if < 2 edges)

    def as_dict(self) -> dict:
        return asdict(self)


def altafini(E, edges, rtol: float = RTOL) -> AltafiniResult:
    E = np.asarray(E, dtype=np.float64)
    K = int(E.size)
    edges = list(edges)
    connected = is_connected(K, edges)
    scale = float(E.max() - E.min()) if K else 0.0
    if not edges or not scale > 0:
        return AltafiniResult(K, len(edges), connected, False, False, False, -1, scale,
                              0.0, float("inf"))
    a = np.array([i for i, _ in edges])
    b = np.array([j for _, j in edges])
    gaps = np.abs(E[a] - E[b])
    tol = rtol * scale
    nonzero = bool(np.all(gaps > tol))
    s = np.sort(gaps)
    seps = np.diff(s)
    distinct = bool(np.all(seps > tol)) if seps.size else True
    holds = connected and nonzero and distinct
    return AltafiniResult(
        K=K, n_edges=len(edges), connected=connected, gaps_nonzero=nonzero, gaps_distinct=distinct,
        holds=holds, d_eff=K * K - 1 if holds else -1, scale=scale,
        min_gap_rel=float(gaps.min() / scale),
        min_sep_rel=float(seps.min() / scale) if seps.size else float("inf"),
    )


def coupling_matrix(K: int, edges) -> np.ndarray:
    H1 = np.zeros((K, K))
    for i, j in edges:
        H1[i, j] = H1[j, i] = 1.0
    return H1


def closure_dim(E, edges, tol: float = 1e-9, max_dim: int | None = None) -> int:
    """Dimension of the Lie algebra generated by i(diag(E) - mean) and i H_1 (the fallback).

    Elements are kept as real vectors (Re, Im) of anti-Hermitian matrices, orthonormalized by
    modified Gram-Schmidt; a bracket is new when its residual norm exceeds `tol` times its norm.
    """
    E = np.asarray(E, dtype=np.float64)
    K = int(E.size)
    cap = max_dim if max_dim is not None else K * K - 1
    gens = [1j * np.diag(E - E.mean()), 1j * coupling_matrix(K, edges)]
    gens = [g / np.linalg.norm(g) for g in gens if np.linalg.norm(g) > 0]
    basis: list[np.ndarray] = []           # orthonormal real vectors of length 2 K^2
    mats: list[np.ndarray] = []

    def vec(M):
        return np.concatenate([M.real.ravel(), M.imag.ravel()])

    def add(M) -> bool:
        v = vec(M)
        nv = np.linalg.norm(v)
        if nv == 0:
            return False
        v = v / nv
        for _ in range(2):                  # re-orthogonalize once for stability
            for w in basis:
                v = v - (w @ v) * w
        r = np.linalg.norm(v)
        if r <= tol:
            return False
        v = v / r
        basis.append(v)
        mats.append((v[: K * K] + 1j * v[K * K:]).reshape(K, K))
        return True

    queue = []
    for g in gens:
        if add(g):
            queue.append(mats[-1])
    while queue and len(basis) < cap:
        x = queue.pop(0)
        for g in gens:
            c = g @ x - x @ g
            if add(c):
                queue.append(mats[-1])
                if len(basis) >= cap:
                    break
    return len(basis)
