"""`reports/sectors.md` (PLAN §5 S2): GA-vs-BF agreement, selection loss, timing (replacing the
completed work's `speed*.csv`), controllability at every confined cell, the standalone
objective-aware GA, and the pybind validation. Built from `results/sectors/*.parquet` only."""

from __future__ import annotations

from pathlib import Path

import numpy as np
import pandas as pd

from .._version import HARNESS_VERSION
from ..store.paths import GSP_ROOT, reports_dir, sectors_dir
from .ga import TABLE_4_1
from .select import load_cells, load_tables

SPEED_CSV = GSP_ROOT.parent / "CUDA" / "speed.csv"      # completed work, read-only reference


def _ms(x) -> str:
    x = np.asarray(x, float)
    x = x[np.isfinite(x)]
    if x.size == 0:
        return "—"
    return f"{1e3 * np.median(x):.3g} [{1e3 * x.min():.3g}–{1e3 * x.max():.3g}]"


def _g(x, fmt="{:.3g}") -> str:
    x = np.asarray(x, float)
    x = x[np.isfinite(x)]
    return "—" if x.size == 0 else fmt.format(np.median(x))


def _pybind_tables(root=None) -> dict:
    d = sectors_dir(root)
    out = {}
    for p in sorted(d.glob("pybind_*.parquet")):
        out[p.stem] = pd.read_parquet(p)
    return out


def _cell_rows(sec: pd.DataFrame):
    """(cell dict, rows of `sec` for that cell's sector files)."""
    for c in load_cells():
        lab = f"{c['connectivity']}|{c['rule']}|K{int(c['K'])}|N{int(c['N'])}"
        rows = sec[sec["cells"].str.split().apply(lambda L: lab in L)]
        yield c, lab, rows


def markdown(root=None) -> str:
    t = load_tables(root)
    runs, sec = t["runs"], t["sectors"]
    pb = _pybind_tables(root)
    P = TABLE_4_1
    L = []
    A = L.append
    A("# Sector selection and preprocessing cost (S2)")
    A("")
    A(f"Generated by `gsp sectors report` from `results/sectors/` (harness_version {HARNESS_VERSION}). "
      "Plan: PLAN §1.2 (cells), §5 S2, D-5, D-6, D-15.")
    A("")
    A(f"- **GA** (numpy, `gsp/sectors/ga.py`): Table 4.1 — population {P.population}, {P.generations} "
      f"generations, r_c = {P.crossover_rate}, r_m = {P.mutation_scale}/n, tournament {P.tournament}, "
      f"elitism {P.elitism}, single-point crossover, bit-flip mutation, the C++ chromosome layout. "
      f"Every run evaluates (G + 1)·N_pop = {(P.generations + 1) * P.population:,} fitnesses. Seeds: "
      "`ga_seed_violation` / `ga_seed_objective` of the seed table.")
    A("- **Rules.** violation: rank by F(x) = (P_bb·x − 1)². objective (D-6): band strings "
      "(|P_bb·x − 1| ≤ ε) first, ranked by H_obj; then the rest by F.")
    A("- **Production = the GA list** (D-15); the brute-force (BF) top-K under the same total order is the "
      "reference. A difference is selection loss; the GA list is still used.")
    A(f"- **Files:** {sec['sector_file'].nunique()} sector files "
      f"({(sec.drop_duplicates('sector_file')['rule'] == 'violation').sum()} violation per draw, "
      f"{(sec.drop_duplicates('sector_file')['rule'] == 'objective').sum()} objective per instance) "
      f"from {int(runs['in_cell'].sum())} GA runs at the cells; {int((~runs['in_cell']).sum())} more runs at "
      "N = 8–10 feed only the timing and by-size tables.")
    A("")

    # --- agreement per cell -------------------------------------------------------------------
    A("## GA vs brute force per cell")
    A("")
    A("One row per §1.2 cell. A violation file is per draw (shared by the three q, and by the ring and "
      "complete cells of the same K); an objective file is per instance. *files = BF*: the GA list equals the "
      "BF list as a set. *missed*: BF strings absent from the GA list, summed over the cell's files. "
      "*best changed*: instances whose best-in-sector energy differs between the two lists; *AR loss*: "
      "min / max over the cell's instances of AR_best(BF list) − AR_best(GA list), with "
      "AR = (E_max − f)/(E_max − E_min) over the band (positive = the miss cost quality, negative = the GA "
      "list happens to hold a better string).")
    A("")
    A("| cell (connectivity · rule · K · N) | draws | files | files = BF | missed strings | best changed (instances) | AR loss min / max |")
    A("|---|---|---|---|---|---|---|")
    for c, lab, rows in _cell_rows(sec):
        files = rows.drop_duplicates("sector_file")
        changed = int((rows["best_f_ga"] != rows["best_f_bf"]).sum())
        d = rows["ar_best_bf"] - rows["ar_best_ga"]
        A(f"| {c['connectivity']} · {c['rule']} · {int(c['K'])} · {int(c['N'])} | {rows['draw_id'].nunique()} "
          f"| {len(files)} | {int(files['identical'].sum())}/{len(files)} | {int(files['n_missing'].sum())} "
          f"| {changed}/{len(rows)} | {d.min():.3g} / {d.max():.3g} |")
    uf = sec.drop_duplicates("sector_file")
    tot_files, tot_same, tot_missed = len(uf), int(uf["identical"].sum()), int(uf["n_missing"].sum())
    tot_changed = int((sec["best_f_ga"] != sec["best_f_bf"]).sum())
    dd = sec["ar_best_bf"] - sec["ar_best_ga"]
    A("")
    A(f"**Total selection loss (all {tot_files} files):** {tot_files - tot_same} files differ from BF, "
      f"{tot_missed} strings missed in total; the best-in-sector energy changes on {tot_changed} of "
      f"{len(sec)} (file, instance) pairs, with AR_best(BF) − AR_best(GA) between {dd.min():.3g} and "
      f"{dd.max():.3g}" + (" (no pair loses quality). " if dd.max() <= 0 else ". ") +
      f"No kept string lies outside the band ({int(uf['n_out_of_band'].sum())} out-of-band strings in total).")
    A("")
    bad = uf[~uf["identical"]]
    if len(bad):
        A("Files that differ from BF: " + ", ".join(f"`{r.sector_file}` ({int(r.n_missing)})"
                                                    for r in bad.itertuples()) + ".")
        A("")

    # --- agreement by size -------------------------------------------------------------------------
    A("## GA vs brute force by size (every K the band can host, N = 4–10)")
    A("")
    A("Per GA run: does the top-K of the final population equal the BF top-K? N = 8–10 has no confined "
      "cell; those runs measure how the Table 4.1 GA degrades with n. Fraction of runs identical "
      "(runs), mean strings missed.")
    A("")
    A("| rule | N | n | " + " | ".join(f"K = {K}" for K in (6, 8, 12, 24)) + " |")
    A("|---|---|---|" + "---|" * 4)
    for (rule, N), g in runs.groupby(["rule", "N"]):
        cells = []
        for K in (6, 8, 12, 24):
            a = g[f"agree_K{K}"].dropna()
            if a.empty:
                cells.append("—")
                continue
            m = g[f"missed_K{K}"].dropna().astype(float)
            cells.append(f"{a.astype(bool).mean():.2f} ({len(a)}), {m.mean():.2f}")
        A(f"| {rule} | {N} | {int(g['n'].iloc[0])} | " + " | ".join(cells) + " |")
    A("")

    # --- quality of the sector vs the band optimum --------------------------------------------------
    A("## Best-in-sector energy vs the band optimum")
    A("")
    A("Per cell, over its instances: the fraction whose production (GA) sector contains the band optimum X*, "
      "and AR_best of the sector (1 = X* inside). This is the price of the violation rule's blindness to "
      "H_obj; the objective rule contains X* by construction whenever the GA finds it.")
    A("")
    A("| cell | instances | X* in sector | AR_best median | AR_best min |")
    A("|---|---|---|---|---|")
    for c, lab, rows in _cell_rows(sec):
        A(f"| {c['connectivity']} · {c['rule']} · {int(c['K'])} · {int(c['N'])} | {len(rows)} "
          f"| {rows['xstar_in_ga'].mean():.2f} | {rows['ar_best_ga'].median():.3f} | {rows['ar_best_ga'].min():.3f} |")
    A("")

    # --- timing ------------------------------------------------------------------------------------
    A("## Timing (replaces `CUDA/speed*.csv`)")
    A("")
    A("Wall-clock per run, median [min–max], one thread (`*_NUM_THREADS=1`), idle machine, sequential. "
      "GA: initialization through the top-K list, excluding the first-evaluation bookkeeping (which is "
      "reported separately in `ga_runs.parquet`). BF: the numpy exhaustive evaluation of all 2^n strings "
      "plus the full ranking. *unique*: distinct strings the GA evaluated (median), as a fraction of 2^n. "
      "C++: the pybind `ga_solver` on the same instances and seeds on this machine (construction + run + "
      "top-K). *speed.csv*: the completed work's medians (different instances, C++ GA time around `run` "
      "only, BF = the old `all_state_to_return` penalty pass), for reference.")
    A("")
    cpp = {}
    for name, df in pb.items():
        if name.startswith("pybind_seed") or df.empty:
            continue
        for (rule, N), g in df.drop_duplicates(["scope_id", "rule"]).groupby(["rule", "N"]):
            cpp.setdefault((rule, N), []).extend(g["cpp_wall_s"].tolist())
    old = None
    if SPEED_CSV.exists():
        o = pd.read_csv(SPEED_CSV)
        old = o.groupby("Assets")[["GA_time_ms", "BF_time_ms"]].median()
    A("| N | n | GA violation ms | GA objective ms | evaluations | unique (frac of 2^n) | C++ violation ms | C++ objective ms | BF violation ms | BF objective ms | speed.csv GA ms | speed.csv BF ms |")
    A("|---|---|---|---|---|---|---|---|---|---|---|---|")
    for N, g in runs.groupby("N"):
        n = int(g["n"].iloc[0])
        v, o_ = g[g["rule"] == "violation"], g[g["rule"] == "objective"]
        uniq = np.median(g["ga_n_unique"])
        oc = f"{old.loc[N, 'GA_time_ms']:.3g}" if old is not None and N in old.index else "—"
        ob = (f"{old.loc[N, 'BF_time_ms']:.3g}" if old is not None and N in old.index
              and np.isfinite(old.loc[N, 'BF_time_ms']) else "—")
        A(f"| {N} | {n} | {_ms(v['ga_wall_s'])} | {_ms(o_['ga_wall_s'])} | {int(g['ga_n_evals'].iloc[0]):,} "
          f"| {uniq:.0f} ({uniq / (1 << n):.3g}) | {_ms(cpp.get(('violation', N), []))} "
          f"| {_ms(cpp.get(('objective', N), []))} | {_ms(v['bf_wall_s'])} | {_ms(o_['bf_wall_s'])} | {oc} | {ob} |")
    A("")
    A(f"Evaluation counts per GA run: violation rule {int(runs.loc[runs.rule == 'violation', 'ga_n_violation_evals'].iloc[0]):,} "
      f"violation evaluations and 0 objective evaluations; objective rule "
      f"{int(runs.loc[runs.rule == 'objective', 'ga_n_objective_evals'].iloc[0]):,} of each (the fitness needs "
      "both). Every sector file carries its run's `ga_wall_s`, `ga_cpu_s`, `ga_n_evals`, "
      "`ga_n_violation_evals`, `ga_n_objective_evals`, `ga_n_unique` and `bf_wall_s` for WP5.")
    A("")

    # --- controllability ---------------------------------------------------------------------------
    A("## Controllability (Altafini) at every confined cell")
    A("")
    A("Per (instance, production sector, connectivity): the coupling graph is connected and the gaps "
      "|E_u − E_v| over its coupled pairs are nonzero and pairwise distinct (tolerance 1e-9 × the sector's "
      "energy spread; E = H_obj on the kept strings). If it holds, d_eff = K² − 1. Ring = K edges over the "
      "lexicographic list (D-9); complete = every pair. A4 has no connectivity axis: its step couples every "
      "pair, so its condition is the complete graph on the 18 ring-row cells. Margins are the smallest "
      "gap and the smallest separation between two gaps, relative to the spread (min over the cell).")
    A("")
    A("| cell | arms | graph | instances | pass | flagged | min gap / spread | min separation / spread | d_eff |")
    A("|---|---|---|---|---|---|---|---|---|")
    n_pass = n_flag = 0
    for c, lab, rows in _cell_rows(sec):
        combos = [("A1, A2c", c["connectivity"])]
        if c["connectivity"] == "ring":
            combos.append(("A4", "complete"))
        for arms, graph in combos:
            h = rows[f"{graph}_holds"].astype(bool)
            n_pass += int(h.sum())
            n_flag += int((~h).sum())
            d = sorted(set(rows[f"{graph}_d_eff"].astype(int)))
            A(f"| {c['connectivity']} · {c['rule']} · {int(c['K'])} · {int(c['N'])} | {arms} | {graph} | {len(rows)} "
              f"| {int(h.sum())} | {int((~h).sum())} | {rows[f'{graph}_min_gap_rel'].min():.2e} "
              f"| {rows[f'{graph}_min_sep_rel'].min():.2e} | {', '.join(str(x) for x in d)} |")
    A("")
    A(f"**Total: {n_pass} pass, {n_flag} flagged** over {n_pass + n_flag} (cell, instance, arm-graph) checks. "
      "Flagged checks fall back to the numerical closure (`control.closure_dim`), whose value is the d_eff shown.")
    A("")
    rr = sec.drop_duplicates(["sector_file", "inst_id"])
    A(f"For reference (D-9 note below): with the ring in the GA's *rank* order instead, the condition holds on "
      f"{int(rr['ring_rank_holds'].sum())}/{len(rr)} (file, instance) pairs.")
    A("")

    # --- standalone GA solver -----------------------------------------------------------------------
    A("## The objective-aware GA as a standalone classical solver (WP5)")
    A("")
    A("The objective-rule runs above, read as a solver: the best string of the final population. "
      "*evals to best*: the evaluation index (1-based, in population order) at which that string was first "
      "evaluated; *evals to X\\**: the same for the band optimum (0 = never). Budget per run: "
      f"{(P.generations + 1) * P.population:,} evaluations.")
    A("")
    A("| N | n | instances | best in band | best = X* | evals to best median [max] | evals to X* median | generation of best median [max] | AR_best median [min] |")
    A("|---|---|---|---|---|---|---|---|---|")
    ob = runs[runs["rule"] == "objective"]
    for N, g in ob.groupby("N"):
        hit = g["solver_hit_xstar"].astype(bool)
        ex = g.loc[g["solver_evals_to_xstar"] > 0, "solver_evals_to_xstar"]
        A(f"| {N} | {int(g['n'].iloc[0])} | {len(g)} | {g['solver_best_in_band'].astype(bool).mean():.2f} "
          f"| {hit.mean():.2f} | {np.median(g['solver_evals_to_best']):.0f} [{g['solver_evals_to_best'].max():.0f}] "
          f"| {_g(ex, '{:.0f}')} | {np.median(g['solver_gen_to_best']):.0f} [{g['solver_gen_to_best'].max():.0f}] "
          f"| {g['solver_ar_best'].astype(float).median():.4f} [{g['solver_ar_best'].astype(float).min():.4f}] |")
    A("")

    # --- pybind validation --------------------------------------------------------------------------
    A("## Validation against the pybind `ga_solver` (D-5)")
    A("")
    if not pb:
        A("The pybind module did not import in the `gsp` env; validation skipped.")
    for name, df in pb.items():
        if df.empty:
            continue
        if name.startswith("pybind_seed"):
            continue
        lab = df["module"].iloc[0]
        A(f"**{lab}** (seeded: {bool(df['seeded'].iloc[0])}). Every §1.2 GA job at N = 4–7, one C++ run "
          "each (with the job's GA seed when the build takes one), every K the band can host. Fraction of "
          "runs whose top-K equals BF (C++ / numpy) and whose C++ and numpy sets agree:")
        A("")
        A("| rule | N | K | runs | C++ = BF | numpy = BF | C++ = numpy |")
        A("|---|---|---|---|---|---|---|")
        for (rule, N, K), g in df.groupby(["rule", "N", "K"]):
            A(f"| {rule} | {N} | {K} | {len(g)} | {g['cpp_eq_bf'].mean():.3f} | {g['numpy_eq_bf'].mean():.3f} "
              f"| {g['cpp_eq_numpy'].mean():.3f} |")
        A("")
    for name, df in pb.items():
        if not name.startswith("pybind_seed") or df.empty:
            continue
        A(f"**Seed study** (`{name}`): the same instances, 10_000 + s for s < {df['seed'].nunique()} as seeds "
          "for both implementations; P(top-K = BF) with its binomial standard error. The two implementations "
          "differ in RNG streams, so they agree in distribution, not run by run.")
        A("")
        A("| instance | rule | K | seeds | C++ = BF | numpy = BF |")
        A("|---|---|---|---|---|---|")
        for (iid, rule, K), g in df.groupby(["inst_id", "rule", "K"]):
            def pm(x):
                p = x.mean()
                return f"{p:.3f} ± {np.sqrt(p * (1 - p) / len(x)):.3f}"
            A(f"| {iid} | {rule} | {K} | {len(g)} | {pm(g['cpp_eq_bf'])} | {pm(g['numpy_eq_bf'])} |")
        A("")

    # --- findings --------------------------------------------------------------------------------------
    A("## Findings for Sensei")
    A("")
    ncell = runs[runs["in_cell"]]
    A("1. **\"Identical at n ≤ 14\" does not hold for the Table 4.1 GA** (the plan's expectation, not a rule). "
      f"{tot_files - tot_same} of {tot_files} production files differ from BF by {tot_missed} strings, all at "
      "N ≥ 5 (see the per-cell table). The C++ `ga_solver` misses at the same rates (seed studies above: "
      "equal within one standard error on every instance/rule/K), and the completed work's own "
      "`CUDA/speed__.csv` shows the same (Assets = 7: 2/10 draws differ at K = 12 and 5/10 at K = 24). "
      "Per D-15 the GA lists stay in production and the misses are the logged selection loss; the best-in-"
      "sector energy never got worse. More generations or a larger population would close the gap but "
      "change Table 4.1, which is Sensei's call.")
    A("2. **Ring order (D-9).** The completed confined runs did *not* order the ring lexicographically: "
      "`CUDA/PO_new_ApproxRatio.py:768-795` builds `T` (the ring) over `init_state` in rank order "
      "(`get_init_states` = `argsort(state_penalty)` for BF sectors; the GA's own ranking for `--GA`). The "
      "sector files store the lexicographic list as `idx` (PLAN §2.2 as written) and the ranking as "
      "`rank_idx`, so S3/S4 can build either; S4's legacy-equivalence test needs the rank-order ring. The "
      "Altafini condition holds in both orders on every (file, instance).")
    A(f"3. **The objective-aware GA always finds X\*** at N = 4–10 ({int(ob['solver_hit_xstar'].sum())}/{len(ob)} "
      "instances) within the 72,000-evaluation budget, typically in the first few generations; as a "
      "standalone solver it reaches AR_best = 1 everywhere in the envelope, which is the WP5 break-even ceiling.")
    A("")

    # --- consistency checks ---------------------------------------------------------------------------
    A("## Consistency checks")
    A("")
    A(f"- The GA's band test |P_bb·x − 1| ≤ ε against the frozen band, over all 2^n strings of every run: "
      f"**{int(runs['n_band_disagree'].sum())}** disagreements.")
    A(f"- The BF ranking against the rulers (band_pen for violation, f_band for objective) at every K the band "
      f"hosts: {int(runs['bf_matches_rulers'].sum())}/{len(runs)} runs match.")
    A(f"- Every GA run returned ≥ 24 distinct strings (min {int(runs['ga_n_distinct_final'].min())} distinct in "
      "the final population).")
    A("")
    return "\n".join(L) + "\n"


def write(root=None) -> Path:
    p = reports_dir() / "sectors.md"
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(markdown(root))
    return p
