"""reports/dbqite.md from results/tables/s8_dbqite.json (S8; `scripts/s8_dbqite_checks.py report`)."""

from __future__ import annotations

import json
from pathlib import Path

import numpy as np


def _e(v, fmt="{:.2e}"):
    return "—" if v is None or (isinstance(v, float) and not np.isfinite(v)) else fmt.format(v)


def _fixture_summary() -> dict | None:
    from ..sim.selfcheck import fixture_path
    p = fixture_path("0.15.1")
    if not p.exists():
        return None
    fx = json.loads(p.read_text())
    return {"path": p.name, "bytes": p.stat().st_size, "n_circuits": len(fx["circuits"]), "schema": fx.get("schema"),
            "db_units": sorted({c.get("step_units", "plan") for c in fx["circuits"] if c["arm"] in ("A4", "A6")}),
            "trajectories": {k: v["n_iter"] for k, v in fx["trajectories"].items()}, "version": fx["cudaq_version"],
            "recorded_at": fx["recorded_at"], "instances": fx["instances"]}


def _cap_model(row: dict, limit_s: float = 600.0) -> dict:
    """Extrapolate a stored timing run (steps 1..T) by 3x per step: loop, logger (same share), run wall per k."""
    st = np.asarray(row["step_wall_s"], dtype=float)
    T = st.size
    ratio = float(np.exp(np.mean(np.log(st[-3:] / st[-4:-1]))))
    loop = float(np.sum(st)) + row["e0_s"]
    share = row["logger_s"] / max(loop, 1e-9)
    post = row.get("postrun_s") or 0.0
    out, step = [], st[-1]
    for k in range(T + 1, 13):
        step *= ratio
        loop += step
        post *= ratio
        out.append({"k": k, "step_s": step, "run_s": loop * (1 + share), "run_plus_post_s": loop * (1 + share) + post})
    cap = T
    for r in out:
        if r["run_s"] <= limit_s:
            cap = r["k"]
    return {"ratio": ratio, "rows": out, "cap_run": cap,
            "cap_run_plus_post": max([T] + [r["k"] for r in out if r["run_plus_post_s"] <= limit_s])}


def markdown(d: dict) -> str:
    L = ["# Arms A4 / A6 (DB-QITE) and Rule C1 — S8, S8b", "",
         "Generated by `scripts/s8_dbqite_checks.py report` from `results/tables/s8_dbqite.json`. RTX 4080, CUDA-Q "
         "0.15.1, target nvidia fp64, `CUDAQ_FUSION_MAX_QUBITS=1`.", ""]
    L += ["## 1. What runs", "",
          "- Step (PLAN §1.5): |psi_{k+1}> = e^{i r H} e^{i r rho_k} e^{-i r H} |psi_k>, r = sqrt(s), "
          "e^{i r rho_k} = U_k e^{i r |0..0><0..0|} U_k^dagger (the leading e^{-i r rho_k} is a global phase, dropped). "
          "U_{k+1} = e^{irH} U_k P(r) U_k^dagger e^{-irH} U_k: 3 copies of U_k per step, 3^k copies of U_0 in U_k. No "
          "projection anywhere.",
          "- Grid {0.02, 0.05, 0.1, 0.2, 0.3, 0.5, 0.8} / sigma_H (sigma_H = std of H's un-boosted diagonal over the "
          "sector (A4) or all 2^n strings (A6)); greedy argmin (first minimum) of the observe energy of the compiled "
          "step; every candidate energy and chosen s is in trajectory.npz (`E_cand`, `s_k`, `g_k`, `grid_idx`).",
          "- A4: U_0 = the S3 star prep over the ring-row cell's GA sector (lex order), H = H_obj, connectivity label "
          "`adaptive`. A6: U_0 = H^n, H = H(lam), lam = 0.005 until S9.",
          "- Simulation: one compiled kernel (`circuits/dbqite_kernel.py`) runs a TOKEN list over two base segments "
          "(U_0, the cost exponential) plus the phase gate (X^n, `r1.ctrl` on the register, X^n). Tokens grow as "
          "(5 * 3^k - 3) / 2 (486 at k = 5, 13,122 at k = 8) while the gate list grows to ~35k (k = 5) and ~0.93M "
          "(k = 8) gates, so kernel-argument overhead (0.8 us per list element, S4) stays negligible. Adjacent cost "
          "exponentials are merged in simulation only (exact up to the rounding of the summed angle).",
          "- Counts (abstract circuit, S3 rules, no cross-segment cancellation): c(U_{k+1}) = 3 c(U_k) + 2 c(cost) + c(P). "
          "The open-controlled phase P: (ii) = 6(n - 2) + 2 CNOTs (V18 chain, n - 2 ancillas); (iii) = the exact "
          "ancilla-free list, sum_{j=1}^{n-1} C_Vale(j) CNOTs (a phase is U(2), not SU(2): see STATUS S8, O-15).",
          "- Charging: step k runs 7 energy circuits of U_k; g2q(t) = sum_{k<=t} 7 c(U_k) (`charge_model: series`).",
          "- Step convention `step_units` (always written into the config, hashed): **`normalized` is the default since "
          "S8b** (PLAN §1.5 as corrected: the circuit carries H / sigma_H, s = g, r = sqrt(g) <= 0.9); `plan` (the S0b "
          "wording: un-boosted H in the circuit, r = sqrt(g / sigma_H) on both factors) is a flag. Both have "
          "r_H r_rho = s (O-13, resolved in S8b).",
          "- Leakage bookkeeping (S8b): every step logs norm, norm_err and, for A4, in_mass (= p_sector), out_mass, "
          "leak_raw = 1 - p_sector and leak_rel = out_mass / norm; the S8 runs got the same fields by replay "
          "(`leakage.npz`, files added only). The aggregate's `leakage` anomaly uses leak_rel for A4 / A6.", ""]
    ex = d.get("example")
    if ex:
        L += ["## 2. `example_dbqite.py` on its 3-qubit instance (Done-when)", "",
              "Grid on the script's unit scale (sigma unit 1, `step_units` plan). The script's trajectory is replayed "
              "with its own `compiled_step` and greedy choice.", "",
              "| k | s script | s GPU | s numpy | E script | E GPU | abs err GPU | abs err numpy | sim gates |",
              "|---|---|---|---|---|---|---|---|---|"]
        for r in ex["rows"]:
            L.append(f"| {r['k'] + 1} | {r['s_script']} | {r['s_gpu']} | {r['s_numpy']} | {r['E_script']:+.6f} | "
                     f"{r['E_gpu']:+.6f} | {r['err_gpu']:.1e} | {r['err_numpy']:.1e} | {r['sim_gates']:,} |")
        L += ["", f"- **s agrees at all 7 steps: {ex['s_agree']}.** Max energy error: GPU {ex['max_err_gpu']:.1e}, numpy "
              f"{ex['max_err_numpy']:.1e}. The GPU error grows ~3x per step (the same gates repeated 3^k times; 2,187 "
              f"copies of U_0 at k = 7). Final state vs the script up to its global phase: {ex['state_err_gpu_vs_script']:.1e}; "
              f"p_ground {ex['p_ground_final']:.3f} (script 0.954).", ""]
    for key in ("c1op", "c1op_plan"):
        op = d.get(key)
        if op:
            L += _c1op_section(op, key)
    for key in ("c1state", "c1state_plan"):
        stt = d.get(key)
        if stt:
            L += _c1state_section(stt, key)
    L += _rest(d)
    return "\n".join(L) + "\n"


def _c1op_section(op: dict, key: str) -> list:
    L = []
    units = op.get("units", "plan")
    if True:
        L += [f"## 3{'' if key == 'c1op' else 'b'}. Rule C1, operator level{' (Done-when)' if key == 'c1op' else ''}: the "
              f"generator [rho_k, H] over every confined cell with n <= 12 — step_units {units}"
              f"{' (the default)' if units == 'normalized' else ' (S8, the flag)'}", "",
              f"A4 ({units} units) for {op['steps']} steps on the GPU; the dense 2^n x 2^n generator of every psi_k, k = 0..{op['steps']}; "
              "off-sector = any element with a row or column outside the kept strings, relative to ||[rho, H]||_2 = "
              f"sqrt(Var_psi H). {op['n_inst']} instances per cell (the first accepted draws, q = 1.5). The 3 complete "
              "cells (K12, N = 4, 5, 6) have no A4 runs of their own: A4 has no connectivity axis and shares the "
              "baseline ring cells' sector files (PLAN §1.2).", "",
              "| cell | axis | n | K | instances | states | max rel | max off-sector element | max off-sector amplitude | pass |",
              "|---|---|---|---|---|---|---|---|---|---|"]
        for r in op["table"]:
            L.append(f"| {r['cell']} | {r['axis']} | {r['n']} | {r['K']} | {r['instances']} | {r['states']} | "
                     f"{r['rel_max']:.1e} | {r['off_max']:.1e} | {r['out_amp_max']:.1e} | {'yes' if r['passes'] else 'NO'} |")
        L += ["", f"- **Max relative off-sector element {op['max_rel']:.1e} (threshold 1e-13): "
              f"{'all cells pass' if op['all_pass'] else 'FAILS'}.**",
              f"- The compiled step itself (npsim on every kept basis string, k = 0, 1, 2, first draw of each cell) against "
              f"the exact reflection formula: off-sector amplitude <= {op['step_operator_max_leak']:.1e}, K x K block error "
              f"<= {op['step_operator_max_block_err']:.1e}.", ""]
        if units == "normalized":
            L += ["- The relative measure is larger than with `plan` units (max 1.4e-16 there): the normalized step "
                  "converges (AR_F ~0.94-0.97 by k = 5), so ||[rho, H]|| = sigma_psi falls to ~1e-5 while the off-sector "
                  "amplitudes stay ~1e-15. The margin to 1e-13 is 3.3x at k = 5 and shrinks as the state converges.", ""]
    return L


def _c1state_section(stt: dict, key: str) -> list:
    L = []
    units = stt.get("units", "plan")
    if True:
        L += [f"## 4{'' if key == 'c1state' else 'b'}. Rule C1, state level: leakage along A4 vs 10 x eps_num — step_units "
              f"{units}", "",
              "leak_k = 1 - p_sector(psi_k) (S5's estimator on both sides), k = 1..5, one instance per ring-row cell "
              "(first draw, q = 1.5). eps_num(n, D_k) = the max |1 - p_sector| over 10 random A1 ring circuits (Eq. 4.11 "
              "parameters, the draw's restart seed) on the same sector at the depth L_k whose multi-controlled gate count "
              "first reaches U_k's (D_k = 3^k mc(U_0) + (3^k - 1)/2).", "",
              "| cell | n | D_k (k = 1..5) | L_k | leak_k | 10 eps_num_k | max ratio | pass | exponent A4 | A1 | max off-sector mass |",
              "|---|---|---|---|---|---|---|---|---|---|---|"]
        for r in stt["rows"]:
            L.append(f"| {r['cell']} | {r['n']} | {', '.join(str(x) for x in r['mc_k'])} | "
                     f"{', '.join(str(x) for x in r['L_matched'])} | {', '.join(f'{v:.1e}' for v in r['leak_k'])} | "
                     f"{', '.join(f'{10 * v:.1e}' for v in r['eps_num_k'])} | {r['max_ratio']:.2f} | "
                     f"{'yes' if r['passes'] else 'NO'} | {r['growth_a4']['exponent']:.2f} ({r['growth_a4']['class']}) | "
                     f"{r['growth_a1']['exponent']:.2f} | {max(r['out_mass_k']):.1e} |")
        pa, p1 = stt["pooled_growth_a4"], stt["pooled_growth_a1"]
        n_pass = sum(r["passes"] for r in stt["rows"])
        L += ["", f"- **{n_pass} / {len(stt['rows'])} cells pass at k <= 5** (max ratio {stt['max_ratio']:.2f}).",
              f"- **Growth exponents (pooled over the cells):** A4 {pa['exponent']:.2f} [{pa['lo']:.2f}, {pa['hi']:.2f}] "
              f"({pa['class']}); the A1 controls {p1['exponent']:.2f} [{p1['lo']:.2f}, {p1['hi']:.2f}] ({p1['class']}).",
              "- **What the A4 'leak' is:** along every trajectory 1 - p_sector = out_mass - norm_err to 2.2e-16, and the "
              f"off-sector mass out_mass is <= {max(max(r['out_mass_k']) for r in stt['rows']):.0e} (second order in the "
              "rounding). The estimator measures the norm "
              "drift. In U_k the same gates (the 3^k copies of U_0 and the repeated cost angles) recur with identical "
              "angles, so their rounding adds coherently (linear in D); the A1 controls draw fresh random angles in every "
              "circuit, so theirs random-walks (sqrt(D)). The linear class is therefore not a confinement bug. With this "
              "estimator the rule would flag A4 at every k >= 6 (the linear-vs-sqrt gap grows as 3^(k/2)). STATUS S8 O-14 "
              "asks Sensei whether C1's state level should use the norm-free off-sector mass.", ""]
        if stt.get("leak_rel_max") is not None:
            L += [f"- The norm-free estimator leak_rel = out_mass / norm: max {stt['leak_rel_max']:.1e} over every cell and "
                  f"step; against the recommended floor 1e-13 (PLAN §4.1 O-14) every cell passes: "
                  f"{stt['leak_rel_passes_1e-13']}.", ""]
    return L


def _rest(d: dict) -> list:
    L = []
    sm = d.get("smoke")
    if sm:
        L += ["## 5. Smoke runs (Done-when): A4 N = 4, 7 (ring-row K12, adaptive), A6 N = 4, 10 (lam 0.005), 5 steps", "",
              "Production store; valid, finalized, aggregated with 0 anomalies. Wall clock per step = the loop's 7 observes "
              "(logger excluded); cumulative (ii) = charged two-qubit executions up to step k.", "",
              "| arm | inst | n | units | s / step, k = 1..5 | cx (ii) of U_k, k = 0..5 | cumulative g2q (ii) at k = 5 | "
              "AR_F k = 0 -> 5 | r_rho |", "|---|---|---|---|---|---|---|---|---|"]
        for r in sm["rows"]:
            L.append(f"| {r['arm']} | {r['inst_id']} | {r['n']} | {r['units']} | "
                     f"{', '.join(f'{v:.3f}' for v in r['step_wall_s'])} | {', '.join(f'{v:,}' for v in r['cx_ii_circuit'])} | "
                     f"{r['g2q_ii_cum'][-1]:,} | {r['ar_f'][0]:.4f} -> {r['ar_f'][-1]:.4f} | "
                     f"{min(r['r_rho'][1:]):.2f}-{max(r['r_rho'][1:]):.2f} |")
        L += ["", "- **O-13 (resolved in S8b: normalized is the default).** With `plan` units the circuit's H is un-boosted (sigma_H ~ 1e-4 for H_obj on a "
              "sector), so r = sqrt(g / sigma_H) = 8-78 rad: the group commutator is far outside its r << 1 regime. To "
              "first order in r H the step is psi + i r (1 - e^{-ir}) (H - E) psi, an effective DB step of r sin r instead "
              "of s = r^2 (45.6 vs 2,079 at N04, g = 0.3). The greedy then picks one g every step and AR_F moves "
              "0.457 -> 0.478 (N = 4) and 0.484 -> 0.506 (N = 7) in 5 steps; with `normalized` units (the example's "
              "regime, r <= 0.9) the same circuits reach 0.968 and 0.938. The gate counts and the wall clock are "
              "identical in both conventions.", ""]
    tm = d.get("time")
    if tm:
        L += ["## 6. Per-step wall clock and the recursion cap (for S9)", "",
              "Stored timing runs, plan units, 8 steps. `run` = loop + logger (run.json wall_s); the post-run step "
              "(state, 1000 shots, simdiff) follows.", "",
              "| arm | inst | n | s / step, k = 1..8 | logger | run | post-run | cx (ii) of U_8 | cumulative g2q (ii) at k = 8 | sim gates of U_8 |",
              "|---|---|---|---|---|---|---|---|---|---|"]
        for r in tm["rows"]:
            L.append(f"| {r['arm']} | {r['inst_id']} | {r['n']} | {', '.join(f'{v:.2f}' for v in r['step_wall_s'])} | "
                     f"{r['logger_s']:.1f} s | {r['run_wall_s']:.1f} s | {_e(r['postrun_s'], '{:.1f} s')} | "
                     f"{r['cx_ii_circuit'][-1]:,} | {r['g2q_ii_cum'][-1]:,} | {r['sim_gates'][-1]:,} |")
        L += ["", "Extrapolation at the measured growth (the geometric mean of the last three step ratios), the logger at "
              "its measured share of the loop and the post-run step scaled with the step:", "",
              "| arm | ratio / step | k = 9: step, run, run + post | k = 10: step, run, run + post | cap (run <= 10 min) | cap (with post-run) |",
              "|---|---|---|---|---|---|"]
        for r in tm["rows"]:
            m = _cap_model(r)
            k9, k10 = m["rows"][0], m["rows"][1]
            L.append(f"| {r['arm']} n = {r['n']} | {m['ratio']:.2f} | {k9['step_s']:.0f} s, {k9['run_s'] / 60:.1f} min, "
                     f"{k9['run_plus_post_s'] / 60:.1f} min | {k10['step_s']:.0f} s, {k10['run_s'] / 60:.1f} min, "
                     f"{k10['run_plus_post_s'] / 60:.1f} min | {m['cap_run']} | {m['cap_run_plus_post']} |")
        L += ["", "Both reach 10 min between k = 9 and k = 10, so the expected cap is 9 at the arms' largest n "
              "(PLAN §1.8: min(12, ...), >= 3). S9 measures it.", ""]
    fx = _fixture_summary()
    if fx:
        L += ["## 7. The self-check fixture (PLAN §3.5)", "",
              f"`tests/fixtures/{fx['path']}` ({fx['bytes'] / 1e3:.0f} kB), recorded {fx['recorded_at']} on CUDA-Q "
              f"{fx['version']}: {fx['n_circuits']} circuits (A0, A1, A2p, A2c, A3, A4, A6 on {', '.join(fx['instances'])}: "
              "observe energy + base64 state) and the trajectories "
              + ", ".join(f"{k} ({v} units)" for k, v in fx["trajectories"].items())
              + f". Schema {fx['schema']}: the A4 / A6 entries name their step_units ({fx['db_units']}). "
              "`gsp selfcheck --compare` on 0.15.1 reproduces all 26 cases bit for bit (errors 0.0); the S8b re-record "
              "left every A0-A3 entry bit-identical to the S8 recording.", ""]
    bf = d.get("backfill")
    if bf:
        w = [r for r in bf["rows"] if r.get("status") == "written"]
        worst = max([max(v for k, v in r.items() if k.startswith("replay_")) for r in w] or [0.0])
        L += ["## 8. Leakage backfill of the S8 runs (S8b)", "",
              f"{len(w)} stored A4 / A6 runs replayed into leakage.npz (per-step norm, in_mass, out_mass, leak_raw, "
              f"leak_rel); the replay equals the stored p_sector / out_mass / norm_err to {worst:.1e}. Nothing else in "
              "the run directories changed.", ""]
    return L


def write(d: dict, path=None) -> Path:
    from ..store.paths import GSP_ROOT
    p = GSP_ROOT / "reports" / "dbqite.md" if path is None else Path(path)
    p.write_text(markdown(d))
    return p
