"""reports/arms.md (S4): legacy equivalence, the completed-work replay, reproduction, anneal check, smoke run,
timing. Reads results/tables/{s4_legacy.json, s4_repro.parquet, s4_anneal.parquet, s4_smoke.parquet,
s4_timing.json}; every number in the report comes from those files."""

from __future__ import annotations

import json
from pathlib import Path

import numpy as np
import pandas as pd

from ..store.paths import reports_dir, tables_dir


def _f(x, nd=4):
    if x is None or (isinstance(x, float) and not np.isfinite(x)):
        return "–"
    if isinstance(x, (bool, np.bool_)):
        return "yes" if x else "no"
    if isinstance(x, (int, np.integer)):
        return str(int(x))
    ax = abs(float(x))
    if ax != 0 and (ax < 1e-3 or ax >= 1e5):
        return f"{float(x):.2e}"
    return f"{float(x):.{nd}f}"


def _table(df: pd.DataFrame, cols, heads=None) -> str:
    heads = heads or cols
    out = ["| " + " | ".join(heads) + " |", "|" + "---|" * len(cols)]
    for _, r in df.iterrows():
        out.append("| " + " | ".join(_f(r[c]) if not isinstance(r[c], str) else r[c] for c in cols) + " |")
    return "\n".join(out)


def _load(root):
    d = tables_dir(root)
    out = {}
    for name in ("s4_legacy.json", "s4_timing.json"):
        p = d / name
        out[name] = json.loads(p.read_text()) if p.exists() else None
    for name in ("s4_repro.parquet", "s4_anneal.parquet", "s4_smoke.parquet"):
        p = d / name
        out[name] = pd.read_parquet(p) if p.exists() else None
    return out


def markdown(root=None) -> str:
    from .checks import anneal_verdict
    t = _load(root)
    L = ["# Arms A0, A1, A2 on the common interface (S4)", "",
         "Generated by `gsp arms report` from `results/tables/s4_*`. Sections: the completed work's convention, "
         "legacy equivalence, reproduction, anneal check, smoke run, timing. PLAN §5 S4.", ""]
    leg = t["s4_legacy.json"]
    if leg:
        L += ["## 1. What the completed runs actually computed", "",
              "Replaying the stored final parameters of the 10 completed N = 5, L = 5 runs "
              "(`experiments_approx_Q2_RAND_S1.0_W0.01_Jh`) through the harness circuits:", ""]
        ev = pd.DataFrame(leg["eval_replay"]["rows"])
        L.append(_table(ev, ["e", "F_size", "A0_stored", "A0_new", "A0_new_boosted_circuit", "A1_stored",
                             "A1_old_kernel", "A1_old_kernel_boosted_circuit", "A1_new_mixer_beta_neg"],
                        ["e", "|F|", "A0 AR2 stored", "A0 harness (un-boosted)", "A0 boosted circuit",
                         "A1 AR2 stored", "A1 old kernel (un-boosted)", "A1 old kernel boosted", "A1 new mixer (beta -> -beta)"]))
        er = leg["eval_replay"]
        L += ["", f"- A0: max |Δ| = {_f(er['A0_max_abs_diff'])} with un-boosted circuit coefficients, "
              f"{_f(er['A0_boosted_max_abs_diff'])} with boosted ones.",
              f"- A1 on the old Pauli kernel: max |Δ| = {_f(er['A1_old_max_abs_diff'])} (un-boosted; the completed runs "
              f"used the fp32 target, ~20k exp_pauli per circuit), {_f(er['A1_old_boosted_max_abs_diff'])} (boosted).",
              f"- The same parameters through the NEW compiled mixer (beta negated): max |Δ| = "
              f"{_f(er['A1_new_max_abs_diff'])}: the mixer change alone moves the final AR_F by this much.",
              "- So the completed runs' circuits carried the **un-boosted** coefficients (the boost scaled only the "
              "observable f); the harness does the same (`circuits/ansatz.py`).", ""]
        ic = leg["init_check"]
        L += [f"Init check (seed table, Eq. 4.11 / legacy_init): the stored first iterate is within lr = 0.01 of "
              f"theta_0 (1 - lr wd) on all 10 draws, both arms (max {_f(ic['max_dev'])}; pass = {ic['pass']}). "
              "The A1 gamma range pi / kappa_min is " +
              f"{_f(min(r['A1_gamma_range'] for r in ic['rows']))} ... {_f(max(r['A1_gamma_range'] for r in ic['rows']))} rad.", ""]
        if "train_replay" in leg:
            tr = pd.DataFrame(leg["train_replay"]["rows"])
            L += ["Trainer replay (the harness trainer, fp64, on the old kernels, vs the stored trajectories):", "",
                  _table(tr, ["arm", "e", "iters", "iters_stored", "df_first10", "df_all", "ar_f", "ar_f_stored",
                              "wall_s"],
                         ["run", "e", "iterations", "stored", "max |Δf| first 10", "max |Δf| all", "AR_F",
                          "stored AR2", "wall (s)"]), ""]
        L += ["## 2. Legacy equivalence (N = 4, K = 12, rank-order ring)", "",
              f"- The numpy port of the old merged Pauli expansion equals the legacy copy as a map "
              f"(pass = {leg['pauli_port']['pass']}; words {', '.join(str(r['n_words']) for r in leg['pauli_port']['rows'])}).",
              f"- The old kernel is the ordered product of exp(+i beta c_P P) over the merged words: max |Δψ| = "
              f"{_f(leg['old_mixer_sign']['max_abs_diff_plus_sign'])}.",
              "- New A1 state vs the old kernel's state, random parameters (gamma from Eq. 4.11), "
              f"{leg['equivalence']['n_samples']} draws per beta scale:", ""]
        eq = pd.DataFrame(leg["equivalence"]["rows"])
        eq["infid_max"] = 1 - eq["fid_mapped_min"]
        eq["infid_mean"] = 1 - eq["fid_mapped_mean"]
        L += [_table(eq, ["beta_scale", "fid_mapped_min", "infid_max", "infid_mean", "fid_unmapped_mean",
                          "leak_old_max", "leak_new_max"],
                     ["beta ~ U[-s, s]", "F(old(β), new(−β)) min", "1 − F max", "1 − F mean",
                      "F(old(β), new(β)) mean", "old leakage max", "new leakage max"]), "",
              "Not equivalent: the two mixers agree to first order in beta (sign mapped), the infidelity grows as "
              "~beta^4, and at the Eq. 4.11 range (s = pi) the mean fidelity is "
              f"{_f(eq.fid_mapped_mean.iloc[-1], 3)}. Hence the band check below.", ""]
    rp = t["s4_repro.parquet"]
    if rp is not None:
        L += ["## 3. Reproduction (N = 5, depth 5, restart 0; A1: BF sector, rank ring, legacy_init; A0: lam = 0.005)",
              "", _table(rp, ["arm", "e", "adhoc", "ar_f", "ar2_completed", "delta", "iterations", "converged",
                              "per_iter_s"],
                         ["arm", "e", "ad hoc", "AR_F (harness)", "AR2 (completed)", "Δ", "iterations", "converged",
                          "s / iteration"]), ""]
        g0, g1 = rp[rp.arm == "A0"], rp[rp.arm == "A1"]
        if len(g0):
            L.append(f"- A0 (same circuit up to exact rewrites): |Δ| ≤ 0.02 on {int((g0.abs_delta <= 0.02).sum())}/"
                     f"{len(g0)} (max {_f(g0.abs_delta.max())}).")
        if len(g1):
            L.append(f"- A1 (new compiled mixer; legacy equivalence does not hold, §2): max |Δ| = {_f(g1.abs_delta.max())}; "
                     f"in the plan's band 0.25-0.8: {int(g1.in_plan_band.sum())}/{len(g1)}; inside the completed N = 5, "
                     f"L = 5 range {_f(g1.completed_band_lo.iloc[0])} ... {_f(g1.completed_band_hi.iloc[0])} (10 draws): "
                     f"{int(((g1.ar_f >= g1.completed_band_lo) & (g1.ar_f <= g1.completed_band_hi)).sum())}/{len(g1)}.")
            if leg and "train_replay" in leg:
                tr = pd.DataFrame(leg["train_replay"]["rows"])
                t1 = tr[tr.arm == "A1_old_kernel"]
                L.append("- For scale: the OLD Pauli kernel trained by the harness (fp64) against the same stored runs "
                         f"(§1) already differs by up to {_f((t1.ar_f - t1.ar_f_stored).abs().max())} (fp32 vs fp64 "
                         "finite differences, then a chaotic 300-step trajectory), so a per-run 0.02 tolerance is out of "
                         "reach for any A1 against fp32 references.")
        L.append("")
    an = t["s4_anneal.parquet"]
    if an is not None:
        v = anneal_verdict(an)
        L += ["## 4. Anneal check (A2, primary schedule (0.2, 3.0), N = 7, q = 1.5, lam = 0.005 for A2p)", "",
              "r(p) = (E(p) − E_min)/(E_max − E_min) over what the arm reaches (all strings of H(lam) for A2p, the "
              "sector's strings of H_obj for A2c); r_start = the start state (p = 0). `pass` (the plan's criterion): "
              "sign −1: r(300) < r(5) < r_start and Spearman(p, r) ≤ −0.8; sign +1: r(300) > r(5) > r_start. "
              "`strict` (S4's own, fixed before the data): also r(300) ≤ 0.1 (−1), or r(300) ≥ 0.9 and Spearman ≥ 0.8 (+1).",
              "", _table(v, ["inst_id", "encoding", "sign", "r_start", "r5", "r300", "r_min", "r_max", "p_at_max",
                             "spearman", "pass", "strict"]), ""]
        piv = an.pivot_table(index=["encoding", "sign"], columns="p", values="r", aggfunc="median")
        L += ["Median r(p) over the 3 instances:", "",
              "| encoding | sign | " + " | ".join(str(c) for c in piv.columns) + " |",
              "|---|---|" + "---|" * len(piv.columns)]
        for (enc, sign), row in piv.iterrows():
            L.append(f"| {enc} | {int(sign):+d} | " + " | ".join(_f(x, 3) for x in row.values) + " |")
        L.append("")
    sm = t["s4_smoke.parquet"]
    if sm is not None:
        g = sm.groupby(["arm", "cell"]).agg(runs=("run_id", "count"), valid=("valid", "sum"),
                                            ar_f_min=("metric_ar_f", "min"), ar_f_max=("metric_ar_f", "max")).reset_index()
        L += ["## 5. Smoke run (N = 4, first accepted draw, q = 1.5; every §1.2 cell at N = 4)", "",
              f"{len(sm)} runs, {int(sm.valid.sum())} valid (run.json schema + status done, every PLAN §1.6 "
              "trajectory field with consistent lengths, probabilities in [0, 1], counts.json).", "",
              _table(g, ["arm", "cell", "runs", "valid", "ar_f_min", "ar_f_max"]), ""]
    tm = t["s4_timing.json"]
    if tm:
        rows = []
        for run in tm["runs"]:
            for r in run["rows"]:
                rows.append({**r, "fusion": run["fusion_max_qubits"]})
        df = pd.DataFrame(rows)
        agg = df.groupby(["case", "engine", "fusion"]).agg(gates=("gates", "median"),
                                                           s=("s_per_iter", "median")).reset_index()
        agg["gates"] = agg["gates"].round().astype(int)
        L += ["## 6. Timing: seconds per training iteration (2L + 1 = 19 observes), median over 3 instances", "",
              "fusion = CUDAQ_FUSION_MAX_QUBITS (4 = the CUDA-Q default, 1 = the harness default). "
              "`logger` rows are one post-update logger call (get_state + metrics).", "",
              _table(agg, ["case", "engine", "fusion", "gates", "s"],
                     ["case", "engine", "fusion", "gates / circuit", "s / iteration"]), ""]
    return "\n".join(L) + "\n"


def write(root=None) -> Path:
    p = reports_dir() / "arms.md"
    p.write_text(markdown(root))
    return p
