"""reports/varqite.md (S7): arms A3 / A3d against example_varqite.py, the flag-qubit P(0...0), the reproduction of the
stored N = 7 M1fC1 / M4C1 runs, the rounding-noise ensemble, the smoke records and the per-step timing. Every number
comes from results/tables/s7_varqite.json (`scripts/s7_varqite_checks.py`) and the run records it names."""

from __future__ import annotations

import json

import numpy as np

from ..store.paths import reports_dir, runs_dir


def _f(x, nd=3):
    if x is None or (isinstance(x, float) and not np.isfinite(x)):
        return "–"
    if isinstance(x, bool):
        return "yes" if x else "no"
    if isinstance(x, int):
        return str(x)
    ax = abs(float(x))
    if ax != 0 and (ax < 1e-3 or ax >= 1e5):
        return f"{float(x):.2e}"
    return f"{float(x):.{nd}f}"


def _tab(rows, cols, heads) -> str:
    out = ["| " + " | ".join(heads) + " |", "|" + "---|" * len(heads)]
    for r in rows:
        out.append("| " + " | ".join(_f(r.get(c)) if not isinstance(r.get(c), str) else r.get(c) for c in cols) + " |")
    return "\n".join(out)


def _rec(arm, rid):
    p = runs_dir() / arm / rid / "run.json"
    return json.loads(p.read_text()) if p.exists() else {}


def markdown(d: dict) -> str:
    L = ["# Arms A3 / A3d: penalty VarQITE (S7)", "",
         "Generated by `scripts/s7_varqite_checks.py report` from `results/tables/s7_varqite.json`. Code: "
         "`gsp/train/mclachlan.py` (the loop), `gsp/arms/varqite.py` (A3, A3d, the observe-only engine, charging), "
         "`gsp/circuits/overlap.py` + `overlap_kernel.py` (the flag-qubit overlap circuit). Instance of the stored runs: "
         "N07e000q1.5 (frozen, accepted), lam = 0.005, L = 5 (p = 10), fp64 (the stored cfg says PRECISION fp64).", ""]
    ex = d.get("example", {}).get("rows", [])
    if ex:
        L += ["## 1. example_varqite.py (3 qubits; dtau 0.01, 401 updates, Tikhonov 1e-6)", "",
              "`exact` = the harness loop with the exact metric and C (M6, numpy test engine); `M1` = the production "
              "estimators (M1 forward stencil + C1 forward FD) on the GPU circuits and in numpy.", "",
              _tab(ex, ["L", "example_E", "exact_vs_example", "m1_gpu_E", "m1_gpu_vs_example", "m1_numpy_E",
                        "gpu_vs_numpy_first10", "gpu_vs_numpy_max", "gpu_vs_numpy_final", "cond_M_max"],
                   ["L", "script E", "|exact - script|", "M1 GPU E", "M1 GPU - script", "M1 numpy E",
                    "GPU-numpy (10 steps)", "GPU-numpy max", "GPU-numpy final", "max cond(M)"]), "",
              "The loop reproduces the script exactly (<= 5e-13). With the production estimators it matches at "
              "L = 1, 2 (<= 5.3e-7); at L = 4, 6 the M1 stencil bias (0.4-0.5 % of |M| at kappa = 0.01, shrinking "
              "linearly with kappa: tests/test_varqite.py) steers a flow with cond(M) up to 5e10 onto another path, and "
              "at L = 6 even GPU and numpy (identical estimators, 1e-15 apart in every fidelity) end 0.88 apart.", ""]
    fl = d.get("flag", {})
    if fl:
        L += ["## 2. Flag-qubit P(0...0) (observe of Z_flag) vs the statevector", "",
              _tab(fl["rows"], ["N", "n", "L", "pairs", "flag_vs_statevector", "flag_vs_old_prob"],
                   ["N", "n", "L", "pairs", "vs statevector (same circuit)", "vs old full-depth 'prob' route"]), "",
              f"Max {_f(fl['max_flag_vs_statevector'])} vs the statevector and {_f(fl['max_flag_vs_old_prob'])} vs the "
              "old driver's `kernel_qaoa_X_overlap` + get_state amplitude (the route of the stored sweep): the 1e-12 "
              "target is met.", ""]
    rp = d.get("repro", {})
    if rp:
        L += ["## 3. Reproduction of the stored N = 7 runs", ""]
        rows = []
        for route, arm in (("M4C1", "A3d"), ("M1fC1", "A3")):
            s = rp[route]
            rows.append({"route": f"{route} ({arm})", "T_stored": s["T_stored"], "T_harness": s["T_harness"],
                         "step1": s["rel_E_steps_1_10"][0], "max50": s["rel_E_max_first50"],
                         "first": s["first_step_rel_gt_1e-6"] or "never", "E_st": s["final_E_stored"],
                         "E_h": s["final_E_harness"], "rmin": f"{s['R_min_neg_harness']} / {s['R_min_neg_stored']}",
                         "T_rep": s["replica_T"], "first_rep": s["replica_first_step_rel_gt_1e-6"] or "never",
                         "E_rep": s["replica_final_E"]})
        L += [_tab(rows, ["route", "T_stored", "T_harness", "step1", "max50", "first", "E_st", "E_h", "rmin", "T_rep",
                          "first_rep", "E_rep"],
                   ["route", "steps stored", "steps harness", "rel dE step 1", "max rel dE, steps 1-50",
                    "first step > 1e-6", "final E stored", "final E harness", "R_min < 0 (harness / stored)",
                    "steps old driver", "old driver: first step > 1e-6", "final E old driver"]), "",
              "Old driver = the verbatim `driver_4routes_20260916.py` code (tests/legacy/varqite_driver_m1f.py), "
              "EXACT_MEASURE prob, fp64, run here on CUDA-Q 0.15.1. Energies are un-boosted.", "",
              "Relative energy error per step, steps 1-10:", ""]
        for route in ("M4C1", "M1fC1"):
            s = rp[route]
            L += [f"- {route}: harness vs stored " + " ".join(_f(v) for v in s["rel_E_steps_1_10"]),
                  f"  old driver vs stored " + " ".join(_f(v) for v in s["replica_rel_E_steps_1_10"]),
                  f"  harness vs old driver " + " ".join(_f(v) for v in s["harness_vs_replica_rel_steps_1_10"])]
        s1 = rp["M1fC1"].get("step1")
        if s1:
            L += ["", "Step 1 of M1fC1, harness (flag route, observe) vs old driver (prob route), at the same theta_0: "
                  f"max |dM| {_f(s1['M_max_abs_diff'])} (|M| <= {_f(s1['M_max_abs'])}; diagonal "
                  f"{_f(s1['M_diag_max_abs_diff'])}), rel dC {_f(s1['C_max_rel_diff'])}, rel d(thetadot) "
                  f"{_f(s1['thetadot_max_rel_diff'])} (|thetadot| up to {_f(s1['thetadot_max_abs'])}). The M1 estimate "
                  f"is indefinite: eigenvalues {', '.join(_f(v) for v in s1['eig_M'][:4])}, ... against Tikhonov 1e-6, "
                  "so (M + 1e-6 I)^-1 amplifies rounding by up to ~1e6: a 1e-11 difference in M becomes ~1e-7 in "
                  "thetadot after one step and grows ~10x per step.", ""]
    en = d.get("ensemble", {})
    if en:
        L += ["## 4. Rounding-noise ensemble of M1fC1 (the 'stored run's noise')", "",
              f"A3 from the Ramp init plus N(0, {en['jitter_rad']:g}) rad per parameter (5 seeds), the unjittered "
              "run and the old driver on 0.15.1:", "",
              _tab(en["members"] + [dict(en["unjittered"], seed="none")], ["seed", "T", "final_E", "ar_f", "p_feas"],
                   ["jitter seed", "steps", "final E", "final AR_F", "final p_feas"]), "",
              f"Final E over the {len(en['final_E_all'])} runs: min {_f(en['final_E_min'])}, median "
              f"{_f(en['final_E_median'])}, max {_f(en['final_E_max'])} (ground E0 {_f(en['E0_ground'])}); steps "
              f"{min(en['T_all'])}-{max(en['T_all'])}. The stored final {_f(en['stored_final_E'])} (265 steps) lies "
              f"inside that range (rank {en['stored_rank_among']} of {len(en['final_E_all'])}): within the run's "
              "rounding noise.", ""]
        w = en.get("worst_member")
        if w:
            L += [f"The outlier (seed {w['seed']}) blew up at step {w['step']}: |thetadot| = {_f(w['thetadot_norm'])} "
                  f"(a {_f(0.1 * w['thetadot_norm'])} rad parameter jump), E {_f(w['E_before'])} -> "
                  f"{_f(w['E_after'])}, cond(M) {_f(w['cond_M'])}, lambda_min(M) ~ {_f(w['eig_min_M'])} = -Tikhonov, "
                  f"so M + 1e-6 I was singular; R_min = {_f(w['R_min'])} > 0 there (with an indefinite M, "
                  "C . thetadot < 0: a heating step, not an R_min < 0 event). It never recovered (E "
                  f"{_f(w['E_at_100_to_300'][0])} at step 100, {_f(w['E_final'])} at 300).", ""]
        L += ["## 5. Finding for Sensei (O-11): the M1fC1 loop amplifies rounding by up to 1 / Tikhonov", "",
              "- The forward-stencil M1 estimate is indefinite (O(delta) bias; lambda_min(M) down to -4e-3 on the A3 "
              "records of §6, while A3d's diagonal M stays >= 0) and Tikhonov 1e-6 does not regularize a negative eigenvalue: when one sits near -1e-6, "
              "(M + 1e-6 I) is singular and the step explodes.",
              "- Two exact fp64 implementations (harness flag route vs the verbatim driver's prob route, 3e-11 apart "
              "in M) separate by 1e-6 at step 3-5 and by 1e-3 at step 6; the verbatim driver on CUDA-Q 0.15.1 does "
              "not reproduce its own stored 0.13 trajectory either (1e-6 at step 5, 98 vs 265 steps).",
              "- A run is deterministic on this machine (logger on / off and reruns are bit-identical), but its final "
              "AR_F is one draw from a wide rounding-noise distribution (0.002-0.107 at N07e000q1.5, L = 5).",
              "- The plan's settings are implemented as written (D-3). Options for Sensei (each changes A3's numbers): "
              "project M onto its PSD part (the old SHOTS branch's `psd`), a larger Tikhonov, or the central stencil. "
              "The M4C1 ablation (A3d) is diagonal (M >= 0) and reproduces to 3.4e-9.", ""]
    sm = d.get("smoke", {})
    tm = d.get("time", {})
    if sm or tm:
        L += ["## 6. Smoke records and per-step timing (lam 0.005; RTX 4080, fp64, fusion 1)", ""]
        rows = []
        for r in sm.get("rows", []) + tm.get("rows", []):
            rec = _rec(r["arm"], r["run_id"])
            jumps = rec.get("metric_jump_steps", rec.get("metric_blowup_steps"))
            rows.append(dict(r, jumps=jumps, eig=rec.get("metric_eig_min_M_min"),
                             angle=rec.get("metric_max_angle_step_max")))
        L += [_tab(rows, ["arm", "inst_id", "n", "L", "steps", "run_id", "s_per_step_median", "logger_s_per_step",
                          "circuits_per_step", "overlap_per_step", "g2q_ii_per_step", "g2q_ii_energy_circuit",
                          "R_min_neg", "jumps", "angle", "eig", "cond_M_max"],
                   ["arm", "instance", "n", "L", "steps", "run_id", "s / step", "logger s / step", "circuits / step",
                    "of which overlaps", "g2q (ii) / step", "(ii) per energy circuit", "R_min < 0 (blow-ups)",
                    "jumps > 1 rad", "max angle jump (rad)", "min eig(M)", "max cond(M)"]), "",
              "s / step = median loop wall clock per step (logger excluded; the logger's get_state + metrics is listed "
              "separately). Circuits per step: A3 = p(p+1)/2 overlaps + p variance + (p + 1) energy; A3d = p + (p + 1); "
              "the first step adds E(theta_0). Blow-up = a step with R_min < 0 (the McLachlan residual bound "
              "violated; Sensei's reading of the stored sweep); jump = a step whose largest gate-angle change "
              "dtau |thetadot_k| gen_scale_k exceeds 1 rad. The first 1-2 steps from the Ramp init are large on every "
              "run (3-40 rad), for both metrics.", ""]
    return "\n".join(L) + "\n"


def write(d: dict) -> str:
    p = reports_dir() / "varqite.md"
    p.write_text(markdown(d))
    return str(p)
