"""The gate-list interpreter kernel (S3): ONE `@cudaq.kernel`, compiled once per process, that runs any
gate list of `gsp.compile.decompose` passed as data (`gsp.circuits.program.encode`).

GENERATED by `scripts/gen_interp_kernel.py`; regenerate rather than hand-edit.

Why (CUDA-Q 0.15.1, RTX 4080; STATUS S3, reports/mixer_counts.md): a builder kernel (`cudaq.make_kernel`,
PLAN §2.4) is JIT-compiled per circuit (1.2 s for the 4,300-gate A1 circuit at n = 14, L = 9) and `get_state`
re-compiles it on EVERY call (1.1 s there). This kernel compiles once per process (~0.4 s) and never again,
whatever the list; `get_state` then costs what `observe` costs (53 ms there; the builder's steady `observe`
is 1.6x faster, 33 ms). The multi-controlled rotations take their controls from a runtime list by
dispatching on the arity (1..19 controls, n <= 20): each branch is a fixed-arity `rx.ctrl` / `ry.ctrl`,
which the kernel language supports.

Opcodes: 0 x, 1 h, 2 s, 3 sdg, 4 t, 5 tdg, 6 cx (control ctl[cs]), 7 rx, 8 ry, 9 rz,
10 mc-rx, 11 mc-ry (controls ctl[cs .. cs + nc - 1], closed). Angle = coef, or coef * p[pidx] if pidx >= 0.
"""

import cudaq


@cudaq.kernel
def kernel_program(n: int, op: list[int], tgt: list[int], cs: list[int], nc: list[int], ctl: list[int],
                   coef: list[float], pidx: list[int], p: list[float]):
    q = cudaq.qvector(n)
    for g in range(len(op)):
        o = op[g]
        tq = tgt[g]
        ang = coef[g]
        if pidx[g] >= 0:
            ang = coef[g] * p[pidx[g]]
        if o == 0:
            x(q[tq])
        elif o == 1:
            h(q[tq])
        elif o == 2:
            s(q[tq])
        elif o == 3:
            sdg(q[tq])
        elif o == 4:
            t(q[tq])
        elif o == 5:
            tdg(q[tq])
        elif o == 6:
            x.ctrl(q[ctl[cs[g]]], q[tq])
        elif o == 7:
            rx(ang, q[tq])
        elif o == 8:
            ry(ang, q[tq])
        elif o == 9:
            rz(ang, q[tq])
        elif o == 10:
            c = cs[g]
            k = nc[g]
            if k == 1:
                rx.ctrl(ang, q[ctl[c]], q[tq])
            elif k == 2:
                rx.ctrl(ang, q[ctl[c]], q[ctl[c + 1]], q[tq])
            elif k == 3:
                rx.ctrl(ang, q[ctl[c]], q[ctl[c + 1]], q[ctl[c + 2]], q[tq])
            elif k == 4:
                rx.ctrl(ang, q[ctl[c]], q[ctl[c + 1]], q[ctl[c + 2]], q[ctl[c + 3]], q[tq])
            elif k == 5:
                rx.ctrl(ang, q[ctl[c]], q[ctl[c + 1]], q[ctl[c + 2]], q[ctl[c + 3]], q[ctl[c + 4]], q[tq])
            elif k == 6:
                rx.ctrl(ang, q[ctl[c]], q[ctl[c + 1]], q[ctl[c + 2]], q[ctl[c + 3]], q[ctl[c + 4]], q[ctl[c + 5]], q[tq])
            elif k == 7:
                rx.ctrl(ang, q[ctl[c]], q[ctl[c + 1]], q[ctl[c + 2]], q[ctl[c + 3]], q[ctl[c + 4]], q[ctl[c + 5]], q[ctl[c + 6]], q[tq])
            elif k == 8:
                rx.ctrl(ang, q[ctl[c]], q[ctl[c + 1]], q[ctl[c + 2]], q[ctl[c + 3]], q[ctl[c + 4]], q[ctl[c + 5]], q[ctl[c + 6]], q[ctl[c + 7]], q[tq])
            elif k == 9:
                rx.ctrl(ang, q[ctl[c]], q[ctl[c + 1]], q[ctl[c + 2]], q[ctl[c + 3]], q[ctl[c + 4]], q[ctl[c + 5]], q[ctl[c + 6]], q[ctl[c + 7]], q[ctl[c + 8]], q[tq])
            elif k == 10:
                rx.ctrl(ang, q[ctl[c]], q[ctl[c + 1]], q[ctl[c + 2]], q[ctl[c + 3]], q[ctl[c + 4]], q[ctl[c + 5]], q[ctl[c + 6]], q[ctl[c + 7]], q[ctl[c + 8]], q[ctl[c + 9]], q[tq])
            elif k == 11:
                rx.ctrl(ang, q[ctl[c]], q[ctl[c + 1]], q[ctl[c + 2]], q[ctl[c + 3]], q[ctl[c + 4]], q[ctl[c + 5]], q[ctl[c + 6]], q[ctl[c + 7]], q[ctl[c + 8]], q[ctl[c + 9]], q[ctl[c + 10]], q[tq])
            elif k == 12:
                rx.ctrl(ang, q[ctl[c]], q[ctl[c + 1]], q[ctl[c + 2]], q[ctl[c + 3]], q[ctl[c + 4]], q[ctl[c + 5]], q[ctl[c + 6]], q[ctl[c + 7]], q[ctl[c + 8]], q[ctl[c + 9]], q[ctl[c + 10]], q[ctl[c + 11]], q[tq])
            elif k == 13:
                rx.ctrl(ang, q[ctl[c]], q[ctl[c + 1]], q[ctl[c + 2]], q[ctl[c + 3]], q[ctl[c + 4]], q[ctl[c + 5]], q[ctl[c + 6]], q[ctl[c + 7]], q[ctl[c + 8]], q[ctl[c + 9]], q[ctl[c + 10]], q[ctl[c + 11]], q[ctl[c + 12]], q[tq])
            elif k == 14:
                rx.ctrl(ang, q[ctl[c]], q[ctl[c + 1]], q[ctl[c + 2]], q[ctl[c + 3]], q[ctl[c + 4]], q[ctl[c + 5]], q[ctl[c + 6]], q[ctl[c + 7]], q[ctl[c + 8]], q[ctl[c + 9]], q[ctl[c + 10]], q[ctl[c + 11]], q[ctl[c + 12]], q[ctl[c + 13]], q[tq])
            elif k == 15:
                rx.ctrl(ang, q[ctl[c]], q[ctl[c + 1]], q[ctl[c + 2]], q[ctl[c + 3]], q[ctl[c + 4]], q[ctl[c + 5]], q[ctl[c + 6]], q[ctl[c + 7]], q[ctl[c + 8]], q[ctl[c + 9]], q[ctl[c + 10]], q[ctl[c + 11]], q[ctl[c + 12]], q[ctl[c + 13]], q[ctl[c + 14]], q[tq])
            elif k == 16:
                rx.ctrl(ang, q[ctl[c]], q[ctl[c + 1]], q[ctl[c + 2]], q[ctl[c + 3]], q[ctl[c + 4]], q[ctl[c + 5]], q[ctl[c + 6]], q[ctl[c + 7]], q[ctl[c + 8]], q[ctl[c + 9]], q[ctl[c + 10]], q[ctl[c + 11]], q[ctl[c + 12]], q[ctl[c + 13]], q[ctl[c + 14]], q[ctl[c + 15]], q[tq])
            elif k == 17:
                rx.ctrl(ang, q[ctl[c]], q[ctl[c + 1]], q[ctl[c + 2]], q[ctl[c + 3]], q[ctl[c + 4]], q[ctl[c + 5]], q[ctl[c + 6]], q[ctl[c + 7]], q[ctl[c + 8]], q[ctl[c + 9]], q[ctl[c + 10]], q[ctl[c + 11]], q[ctl[c + 12]], q[ctl[c + 13]], q[ctl[c + 14]], q[ctl[c + 15]], q[ctl[c + 16]], q[tq])
            elif k == 18:
                rx.ctrl(ang, q[ctl[c]], q[ctl[c + 1]], q[ctl[c + 2]], q[ctl[c + 3]], q[ctl[c + 4]], q[ctl[c + 5]], q[ctl[c + 6]], q[ctl[c + 7]], q[ctl[c + 8]], q[ctl[c + 9]], q[ctl[c + 10]], q[ctl[c + 11]], q[ctl[c + 12]], q[ctl[c + 13]], q[ctl[c + 14]], q[ctl[c + 15]], q[ctl[c + 16]], q[ctl[c + 17]], q[tq])
            elif k == 19:
                rx.ctrl(ang, q[ctl[c]], q[ctl[c + 1]], q[ctl[c + 2]], q[ctl[c + 3]], q[ctl[c + 4]], q[ctl[c + 5]], q[ctl[c + 6]], q[ctl[c + 7]], q[ctl[c + 8]], q[ctl[c + 9]], q[ctl[c + 10]], q[ctl[c + 11]], q[ctl[c + 12]], q[ctl[c + 13]], q[ctl[c + 14]], q[ctl[c + 15]], q[ctl[c + 16]], q[ctl[c + 17]], q[ctl[c + 18]], q[tq])
        elif o == 11:
            c = cs[g]
            k = nc[g]
            if k == 1:
                ry.ctrl(ang, q[ctl[c]], q[tq])
            elif k == 2:
                ry.ctrl(ang, q[ctl[c]], q[ctl[c + 1]], q[tq])
            elif k == 3:
                ry.ctrl(ang, q[ctl[c]], q[ctl[c + 1]], q[ctl[c + 2]], q[tq])
            elif k == 4:
                ry.ctrl(ang, q[ctl[c]], q[ctl[c + 1]], q[ctl[c + 2]], q[ctl[c + 3]], q[tq])
            elif k == 5:
                ry.ctrl(ang, q[ctl[c]], q[ctl[c + 1]], q[ctl[c + 2]], q[ctl[c + 3]], q[ctl[c + 4]], q[tq])
            elif k == 6:
                ry.ctrl(ang, q[ctl[c]], q[ctl[c + 1]], q[ctl[c + 2]], q[ctl[c + 3]], q[ctl[c + 4]], q[ctl[c + 5]], q[tq])
            elif k == 7:
                ry.ctrl(ang, q[ctl[c]], q[ctl[c + 1]], q[ctl[c + 2]], q[ctl[c + 3]], q[ctl[c + 4]], q[ctl[c + 5]], q[ctl[c + 6]], q[tq])
            elif k == 8:
                ry.ctrl(ang, q[ctl[c]], q[ctl[c + 1]], q[ctl[c + 2]], q[ctl[c + 3]], q[ctl[c + 4]], q[ctl[c + 5]], q[ctl[c + 6]], q[ctl[c + 7]], q[tq])
            elif k == 9:
                ry.ctrl(ang, q[ctl[c]], q[ctl[c + 1]], q[ctl[c + 2]], q[ctl[c + 3]], q[ctl[c + 4]], q[ctl[c + 5]], q[ctl[c + 6]], q[ctl[c + 7]], q[ctl[c + 8]], q[tq])
            elif k == 10:
                ry.ctrl(ang, q[ctl[c]], q[ctl[c + 1]], q[ctl[c + 2]], q[ctl[c + 3]], q[ctl[c + 4]], q[ctl[c + 5]], q[ctl[c + 6]], q[ctl[c + 7]], q[ctl[c + 8]], q[ctl[c + 9]], q[tq])
            elif k == 11:
                ry.ctrl(ang, q[ctl[c]], q[ctl[c + 1]], q[ctl[c + 2]], q[ctl[c + 3]], q[ctl[c + 4]], q[ctl[c + 5]], q[ctl[c + 6]], q[ctl[c + 7]], q[ctl[c + 8]], q[ctl[c + 9]], q[ctl[c + 10]], q[tq])
            elif k == 12:
                ry.ctrl(ang, q[ctl[c]], q[ctl[c + 1]], q[ctl[c + 2]], q[ctl[c + 3]], q[ctl[c + 4]], q[ctl[c + 5]], q[ctl[c + 6]], q[ctl[c + 7]], q[ctl[c + 8]], q[ctl[c + 9]], q[ctl[c + 10]], q[ctl[c + 11]], q[tq])
            elif k == 13:
                ry.ctrl(ang, q[ctl[c]], q[ctl[c + 1]], q[ctl[c + 2]], q[ctl[c + 3]], q[ctl[c + 4]], q[ctl[c + 5]], q[ctl[c + 6]], q[ctl[c + 7]], q[ctl[c + 8]], q[ctl[c + 9]], q[ctl[c + 10]], q[ctl[c + 11]], q[ctl[c + 12]], q[tq])
            elif k == 14:
                ry.ctrl(ang, q[ctl[c]], q[ctl[c + 1]], q[ctl[c + 2]], q[ctl[c + 3]], q[ctl[c + 4]], q[ctl[c + 5]], q[ctl[c + 6]], q[ctl[c + 7]], q[ctl[c + 8]], q[ctl[c + 9]], q[ctl[c + 10]], q[ctl[c + 11]], q[ctl[c + 12]], q[ctl[c + 13]], q[tq])
            elif k == 15:
                ry.ctrl(ang, q[ctl[c]], q[ctl[c + 1]], q[ctl[c + 2]], q[ctl[c + 3]], q[ctl[c + 4]], q[ctl[c + 5]], q[ctl[c + 6]], q[ctl[c + 7]], q[ctl[c + 8]], q[ctl[c + 9]], q[ctl[c + 10]], q[ctl[c + 11]], q[ctl[c + 12]], q[ctl[c + 13]], q[ctl[c + 14]], q[tq])
            elif k == 16:
                ry.ctrl(ang, q[ctl[c]], q[ctl[c + 1]], q[ctl[c + 2]], q[ctl[c + 3]], q[ctl[c + 4]], q[ctl[c + 5]], q[ctl[c + 6]], q[ctl[c + 7]], q[ctl[c + 8]], q[ctl[c + 9]], q[ctl[c + 10]], q[ctl[c + 11]], q[ctl[c + 12]], q[ctl[c + 13]], q[ctl[c + 14]], q[ctl[c + 15]], q[tq])
            elif k == 17:
                ry.ctrl(ang, q[ctl[c]], q[ctl[c + 1]], q[ctl[c + 2]], q[ctl[c + 3]], q[ctl[c + 4]], q[ctl[c + 5]], q[ctl[c + 6]], q[ctl[c + 7]], q[ctl[c + 8]], q[ctl[c + 9]], q[ctl[c + 10]], q[ctl[c + 11]], q[ctl[c + 12]], q[ctl[c + 13]], q[ctl[c + 14]], q[ctl[c + 15]], q[ctl[c + 16]], q[tq])
            elif k == 18:
                ry.ctrl(ang, q[ctl[c]], q[ctl[c + 1]], q[ctl[c + 2]], q[ctl[c + 3]], q[ctl[c + 4]], q[ctl[c + 5]], q[ctl[c + 6]], q[ctl[c + 7]], q[ctl[c + 8]], q[ctl[c + 9]], q[ctl[c + 10]], q[ctl[c + 11]], q[ctl[c + 12]], q[ctl[c + 13]], q[ctl[c + 14]], q[ctl[c + 15]], q[ctl[c + 16]], q[ctl[c + 17]], q[tq])
            elif k == 19:
                ry.ctrl(ang, q[ctl[c]], q[ctl[c + 1]], q[ctl[c + 2]], q[ctl[c + 3]], q[ctl[c + 4]], q[ctl[c + 5]], q[ctl[c + 6]], q[ctl[c + 7]], q[ctl[c + 8]], q[ctl[c + 9]], q[ctl[c + 10]], q[ctl[c + 11]], q[ctl[c + 12]], q[ctl[c + 13]], q[ctl[c + 14]], q[ctl[c + 15]], q[ctl[c + 16]], q[ctl[c + 17]], q[ctl[c + 18]], q[tq])
